from mem_dixy.Unicode.U0000 import SPACE
from mem_dixy.Unicode.U0000 import EXCLAMATION_MARK
from mem_dixy.Unicode.U0000 import QUOTATION_MARK
from mem_dixy.Unicode.U0000 import DOLLAR_SIGN
from mem_dixy.Unicode.U0000 import ASTERISK
from mem_dixy.Unicode.U0000 import COMMA
from mem_dixy.Unicode.U0000 import HYPHEN_MINUS
from mem_dixy.Unicode.U0000 import SOLIDUS
from mem_dixy.Unicode.U0000 import QUESTION_MARK
from mem_dixy.Unicode.U0000 import COMMERCIA_AT
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_A
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_C
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_E
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_I
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_N
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_O
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_U
from mem_dixy.Unicode.U0000 import LATIN_CAPITAL_LETTER_Y
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_A
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_C
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_E
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_I
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_N
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_O
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_U
from mem_dixy.Unicode.U0000 import LATIN_SMALL_LETTER_Y
from mem_dixy.Unicode.U0000 import VERTICAL_LINE

from mem_dixy.Unicode.U0080 import U0080
from mem_dixy.Unicode.U0080 import U0081
from mem_dixy.Unicode.U0080 import BREAK_PERMITTED_HERE
from mem_dixy.Unicode.U0080 import NO_BREAK_HERE
from mem_dixy.Unicode.U0080 import INDEX
from mem_dixy.Unicode.U0080 import NEXT_LINE
from mem_dixy.Unicode.U0080 import START_OF_SELECTED_AREA
from mem_dixy.Unicode.U0080 import END_OF_SELECTED_AREA
from mem_dixy.Unicode.U0080 import CHARACTER_TABULATION_SET
from mem_dixy.Unicode.U0080 import CHARACTER_TABULATION_WITHJUSTIFICATION
from mem_dixy.Unicode.U0080 import LINE_TABULATION_SET
from mem_dixy.Unicode.U0080 import PARTIAL_LINE_FORWARD
from mem_dixy.Unicode.U0080 import PARTIAL_LINE_BACKWARD
from mem_dixy.Unicode.U0080 import REVERSE_LINE_FEED
from mem_dixy.Unicode.U0080 import SINGLE_SHIFT_TWO
from mem_dixy.Unicode.U0080 import SINGLE_SHIFT_THREE
from mem_dixy.Unicode.U0080 import DEVICE_CONTROL_STRING
from mem_dixy.Unicode.U0080 import PRIVATE_USE_ONE
from mem_dixy.Unicode.U0080 import PRIVATE_USE_TWO
from mem_dixy.Unicode.U0080 import SET_TRANSMIT_STATE
from mem_dixy.Unicode.U0080 import CANCEL_CHARACTER
from mem_dixy.Unicode.U0080 import MESSAGE_WAITING
from mem_dixy.Unicode.U0080 import START_OF_GUARDED_AREA
from mem_dixy.Unicode.U0080 import END_OF_GUARDED_AREA
from mem_dixy.Unicode.U0080 import START_OF_STRING
from mem_dixy.Unicode.U0080 import U0099
from mem_dixy.Unicode.U0080 import SINGLE_CHARACTER_INTRODUCER
from mem_dixy.Unicode.U0080 import CONTROL_SEQUENCE_INTRODUCER
from mem_dixy.Unicode.U0080 import STRING_TERMINATOR
from mem_dixy.Unicode.U0080 import OPERATING_SYSTEM_COMMAND
from mem_dixy.Unicode.U0080 import PRIVACY_MESSAGE
from mem_dixy.Unicode.U0080 import APPLICATION_PROGRAM_COMMAND
from mem_dixy.Unicode.U0080 import NO_BREAK_SPACE
from mem_dixy.Unicode.U0080 import INVERTED_EXCLAMATION_MARK
from mem_dixy.Unicode.U0080 import CENT_SIGN
from mem_dixy.Unicode.U0080 import POUND_SIGN
from mem_dixy.Unicode.U0080 import CURRENCY_SIGN
from mem_dixy.Unicode.U0080 import YEN_SIGN
from mem_dixy.Unicode.U0080 import BROKEN_BAR
from mem_dixy.Unicode.U0080 import SECTION_SIGN
from mem_dixy.Unicode.U0080 import DIAERESIS
from mem_dixy.Unicode.U0080 import COPYRIGHT_SIGN
from mem_dixy.Unicode.U0080 import FEMININE_ORDINAL_INDICATOR
from mem_dixy.Unicode.U0080 import LEFT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK
from mem_dixy.Unicode.U0080 import NOT_SIGN
from mem_dixy.Unicode.U0080 import SOFT_HYPHEN
from mem_dixy.Unicode.U0080 import REGISTERED_SIGN
from mem_dixy.Unicode.U0080 import MACRON
from mem_dixy.Unicode.U0080 import DEGREE_SIGN
from mem_dixy.Unicode.U0080 import PLUS_MINUS_SIGN
from mem_dixy.Unicode.U0080 import SUPERSCRIPT_TWO
from mem_dixy.Unicode.U0080 import SUPERSCRIPT_THREE
from mem_dixy.Unicode.U0080 import ACUTE_ACCENT
from mem_dixy.Unicode.U0080 import MICRO_SIGN
from mem_dixy.Unicode.U0080 import PILCROW_SIGN
from mem_dixy.Unicode.U0080 import MIDDLE_DOT
from mem_dixy.Unicode.U0080 import CEDILLA
from mem_dixy.Unicode.U0080 import SUPERSCRIPT_ONE
from mem_dixy.Unicode.U0080 import MASCULINE_ORDINAL_INDICATOR
from mem_dixy.Unicode.U0080 import RIGHT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK
from mem_dixy.Unicode.U0080 import VULGAR_FRACTION_ONE_QUARTER
from mem_dixy.Unicode.U0080 import VULGAR_FRACTION_ONE_HALF
from mem_dixy.Unicode.U0080 import VULGAR_FRACTION_THREE_QUARTERS
from mem_dixy.Unicode.U0080 import INVERTED_QUESTION_MARK
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_A_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_A_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_A_WITH_TILDE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_AE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_C_WITH_CEDILLA
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_E_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_E_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_I_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_I_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_ETH
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_N_WITH_TILDE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_O_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_O_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_O_WITH_TILDE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import MULTIPLICATION_SIGN
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_O_WITH_STROKE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_U_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_U_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_Y_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_CAPITAL_LETTER_THORN
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_SHARP_S
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_A_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_A_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_A_WITH_TILDE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_A_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_A_WITH_RING_ABOVE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_AE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_C_WITH_CEDILLA
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_E_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_E_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_E_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_I_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_I_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_I_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_ETH
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_N_WITH_TILDE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_O_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_O_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_O_WITH_TILDE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_O_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import DIVISION_SIGN
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_O_WITH_STROKE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_U_WITH_GRAVE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_U_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_U_WITH_DIAERESIS
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_Y_WITH_ACUTE
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_THORN
from mem_dixy.Unicode.U0080 import LATIN_SMALL_LETTER_Y_WITH_DIAERESIS


C1_CONTROLS_AND_LATIN_1_SUPPLEMENT = {
    U0080: None,
    U0081: None,
    BREAK_PERMITTED_HERE: None,
    NO_BREAK_HERE: None,
    INDEX: None,
    NEXT_LINE: None,
    START_OF_SELECTED_AREA: None,
    END_OF_SELECTED_AREA: None,
    CHARACTER_TABULATION_SET: None,
    CHARACTER_TABULATION_WITHJUSTIFICATION: None,
    LINE_TABULATION_SET: None,
    PARTIAL_LINE_FORWARD: None,
    PARTIAL_LINE_BACKWARD: None,
    REVERSE_LINE_FEED: None,
    SINGLE_SHIFT_TWO: None,
    SINGLE_SHIFT_THREE: None,
    DEVICE_CONTROL_STRING: None,
    PRIVATE_USE_ONE: None,
    PRIVATE_USE_TWO: None,
    SET_TRANSMIT_STATE: None,
    CANCEL_CHARACTER: None,
    MESSAGE_WAITING: None,
    START_OF_GUARDED_AREA: None,
    END_OF_GUARDED_AREA: None,
    START_OF_STRING: None,
    U0099: None,
    SINGLE_CHARACTER_INTRODUCER: None,
    CONTROL_SEQUENCE_INTRODUCER: None,
    STRING_TERMINATOR: None,
    OPERATING_SYSTEM_COMMAND: None,
    PRIVACY_MESSAGE: None,
    APPLICATION_PROGRAM_COMMAND: None,
    NO_BREAK_SPACE: SPACE,
    INVERTED_EXCLAMATION_MARK: EXCLAMATION_MARK,
    CENT_SIGN: DOLLAR_SIGN,
    POUND_SIGN: DOLLAR_SIGN,
    CURRENCY_SIGN: DOLLAR_SIGN,
    YEN_SIGN: DOLLAR_SIGN,
    BROKEN_BAR: VERTICAL_LINE,
    SECTION_SIGN: None,
    DIAERESIS: None,
    COPYRIGHT_SIGN: COMMERCIA_AT,
    FEMININE_ORDINAL_INDICATOR: None,
    LEFT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK: QUOTATION_MARK,
    NOT_SIGN: None,
    SOFT_HYPHEN: HYPHEN_MINUS,
    REGISTERED_SIGN: COMMERCIA_AT,
    MACRON: None,
    DEGREE_SIGN: None,
    PLUS_MINUS_SIGN: None,
    SUPERSCRIPT_TWO: None,
    SUPERSCRIPT_THREE: None,
    ACUTE_ACCENT: None,
    MICRO_SIGN: None,
    PILCROW_SIGN: None,
    MIDDLE_DOT: COMMA,
    CEDILLA: None,
    SUPERSCRIPT_ONE: None,
    MASCULINE_ORDINAL_INDICATOR: None,
    RIGHT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK: QUOTATION_MARK,
    VULGAR_FRACTION_ONE_QUARTER: None,
    VULGAR_FRACTION_ONE_HALF: None,
    VULGAR_FRACTION_THREE_QUARTERS: None,
    INVERTED_QUESTION_MARK: QUESTION_MARK,
    LATIN_CAPITAL_LETTER_A_WITH_GRAVE: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_ACUTE: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_TILDE: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_AE: None,
    LATIN_CAPITAL_LETTER_C_WITH_CEDILLA: LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_E_WITH_GRAVE: LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_E_WITH_ACUTE: LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX: LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS: LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_I_WITH_GRAVE: LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_I_WITH_ACUTE: LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX: LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS: LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_ETH: None,
    LATIN_CAPITAL_LETTER_N_WITH_TILDE: LATIN_CAPITAL_LETTER_N,
    LATIN_CAPITAL_LETTER_O_WITH_GRAVE: LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_ACUTE: LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX: LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_TILDE: LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS: LATIN_CAPITAL_LETTER_O,
    MULTIPLICATION_SIGN: ASTERISK,
    LATIN_CAPITAL_LETTER_O_WITH_STROKE: LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_U_WITH_GRAVE: LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_U_WITH_ACUTE: LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX: LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS: LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_Y_WITH_ACUTE: LATIN_CAPITAL_LETTER_Y,
    LATIN_CAPITAL_LETTER_THORN: None,
    LATIN_SMALL_LETTER_SHARP_S: None,
    LATIN_SMALL_LETTER_A_WITH_GRAVE: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_ACUTE: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_TILDE: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_DIAERESIS: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_RING_ABOVE: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_AE: None,
    LATIN_SMALL_LETTER_C_WITH_CEDILLA: LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_E_WITH_GRAVE: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_E_WITH_ACUTE: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_E_WITH_DIAERESIS: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_I_WITH_GRAVE: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_I_WITH_ACUTE: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_I_WITH_DIAERESIS: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_ETH: None,
    LATIN_SMALL_LETTER_N_WITH_TILDE: LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O_WITH_GRAVE: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_ACUTE: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_TILDE: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_DIAERESIS: LATIN_SMALL_LETTER_O,
    DIVISION_SIGN: SOLIDUS,
    LATIN_SMALL_LETTER_O_WITH_STROKE: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_U_WITH_GRAVE: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_U_WITH_ACUTE: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_U_WITH_DIAERESIS: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_Y_WITH_ACUTE: LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_THORN: None,
    LATIN_SMALL_LETTER_Y_WITH_DIAERESIS: LATIN_SMALL_LETTER_U
}
