from mem_dixy.Unicode.U0000 import *
from mem_dixy.Unicode.U0080 import *

from mem_dixy.Unicode_Encoding.U0000 import encoding as Basic_Latin
from mem_dixy.Unicode_Encoding.U0080 import encoding as Latin_1_Supplement


# convert = Basic_Latin | Latin_1_Supplement # NOTE: 3.9+ ONLY
convert = {**Basic_Latin, **Latin_1_Supplement}


lowercase = {
    LATIN_CAPITAL_LETTER_A: LATIN_SMALL_LETTER_A,
    LATIN_CAPITAL_LETTER_B: LATIN_SMALL_LETTER_B,
    LATIN_CAPITAL_LETTER_C: LATIN_SMALL_LETTER_C,
    LATIN_CAPITAL_LETTER_D: LATIN_SMALL_LETTER_D,
    LATIN_CAPITAL_LETTER_E: LATIN_SMALL_LETTER_E,
    LATIN_CAPITAL_LETTER_F: LATIN_SMALL_LETTER_F,
    LATIN_CAPITAL_LETTER_G: LATIN_SMALL_LETTER_G,
    LATIN_CAPITAL_LETTER_H: LATIN_SMALL_LETTER_H,
    LATIN_CAPITAL_LETTER_I: LATIN_SMALL_LETTER_I,
    LATIN_CAPITAL_LETTER_J: LATIN_SMALL_LETTER_J,
    LATIN_CAPITAL_LETTER_K: LATIN_SMALL_LETTER_K,
    LATIN_CAPITAL_LETTER_L: LATIN_SMALL_LETTER_L,
    LATIN_CAPITAL_LETTER_M: LATIN_SMALL_LETTER_M,
    LATIN_CAPITAL_LETTER_N: LATIN_SMALL_LETTER_N,
    LATIN_CAPITAL_LETTER_O: LATIN_SMALL_LETTER_O,
    LATIN_CAPITAL_LETTER_P: LATIN_SMALL_LETTER_P,
    LATIN_CAPITAL_LETTER_Q: LATIN_SMALL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R: LATIN_SMALL_LETTER_R,
    LATIN_CAPITAL_LETTER_S: LATIN_SMALL_LETTER_S,
    LATIN_CAPITAL_LETTER_T: LATIN_SMALL_LETTER_T,
    LATIN_CAPITAL_LETTER_U: LATIN_SMALL_LETTER_U,
    LATIN_CAPITAL_LETTER_V: LATIN_SMALL_LETTER_V,
    LATIN_CAPITAL_LETTER_W: LATIN_SMALL_LETTER_W,
    LATIN_CAPITAL_LETTER_X: LATIN_SMALL_LETTER_X,
    LATIN_CAPITAL_LETTER_Y: LATIN_SMALL_LETTER_Y,
    LATIN_CAPITAL_LETTER_Z: LATIN_SMALL_LETTER_Z,
    LOW_LINE: LOW_LINE,
    LATIN_SMALL_LETTER_A: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B: LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C: LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D: LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F: LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G: LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H: LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J: LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K: LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L: LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M: LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N: LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P: LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q: LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R: LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S: LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T: LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V: LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W: LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X: LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y: LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z: LATIN_SMALL_LETTER_Z,
}

number = {
    DIGIT_ZERO,
    DIGIT_ONE,
    DIGIT_TWO,
    DIGIT_THREE,
    DIGIT_FOUR,
    DIGIT_FIVE,
    DIGIT_SIX,
    DIGIT_SEVEN,
    DIGIT_EIGHT,
    DIGIT_NINE,
    LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_D,
    LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F,
}

tag = {
    LOW_LINE,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z
}

space = {
    SPACE
}

symbol = {
    EXCLAMATION_MARK: EXCLAMATION_MARK,
    QUOTATION_MARK: QUOTATION_MARK,
    NUMBER_SIGN: NUMBER_SIGN,
    DOLLAR_SIGN: DOLLAR_SIGN,
}

sql_and = {
    AMPERSAND
}

sql_is = {
    PLUS_SIGN
}

sql_not = {
    HYPHEN_MINUS
}

sql_or = {
    VERTICAL_LINE
}

logica_operator = sql_and | sql_is | sql_not | sql_or


two_token = {
    DIGIT_ZERO,
    DIGIT_ONE,
    DIGIT_TWO,
    DIGIT_THREE,
    DIGIT_FOUR,
    DIGIT_FIVE,
    DIGIT_SIX,
    DIGIT_SEVEN,
    DIGIT_EIGHT,
    DIGIT_NINE,
    LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_D,
    LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F,
    LATIN_CAPITAL_LETTER_G,
    LATIN_CAPITAL_LETTER_H,
    LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_J,
    LATIN_CAPITAL_LETTER_K,
    LATIN_CAPITAL_LETTER_L,
    LATIN_CAPITAL_LETTER_M,
    LATIN_CAPITAL_LETTER_N,
    LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_P,
    LATIN_CAPITAL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R,
    LATIN_CAPITAL_LETTER_S,
    LATIN_CAPITAL_LETTER_T,
    LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_V,
    LATIN_CAPITAL_LETTER_W,
    LATIN_CAPITAL_LETTER_X,
    LATIN_CAPITAL_LETTER_Y,
    LATIN_CAPITAL_LETTER_Z,
    LOW_LINE,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z
}


one_token = {
    EXCLAMATION_MARK,
    QUOTATION_MARK,
    NUMBER_SIGN,
    DOLLAR_SIGN,
    PERCENT_SIGN,
    AMPERSAND,
    APOSTROPHE,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    ASTERISK,
    PLUS_SIGN,
    COMMA,
    HYPHEN_MINUS,
    FULL_STOP,
    SOLIDUS,
    COLON,
    SEMICOLON,
    LESS_THAN_SIGN,
    EQUALS_SIGN,
    GREATER_THAN_SIGN,
    QUESTION_MARK,
    COMMERCIA_AT,
    LEFT_SQUARE_BRACKET,
    REVERSE_SOLIDUS,
    RIGHT_SQUARE_BRACKET,
    CIRCUMFLEX_ACCENT,
    GRAVE_ACCENT,
    LEFT_CURLY_BRACKET,
    VERTICAL_LINE,
    RIGHT_CURLY_BRACKET,
    TILDE,
}

all_token = one_token | two_token
