version = 1

test_patterns = [
    "tests/**",
    "test_*.py",
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt"]

    [analyzers.meta]
    runtime_version = "3.12.x"
    type_checker = "mypy"
    max_line_length = 79
    skip_doc_coverage = []
    additional_builtins = []

[[transformers]]
name = "black"
enabled = true
