build:
    apt_packages: []
    jobs: {}
    os: ubuntu-22.04
    tools:
        python: "3.10"

formats: []

python:
    system_packages: true

sphinx:
    builder: dirhtml
    configuration: documentation/conf.py
    fail_on_warning: true

version: 2
