build:
    apt_packages: []
    jobs: {}
    os: ubuntu-22.04
    tools:
        python: "3.11"

formats: []

python:
    system_packages: true
    install:
        - requirements: requirements.txt

sphinx:
    builder: dirhtml
    configuration: documentation/conf.py
    fail_on_warning: true

version: 2
