[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 72

[tool.pylint.format]
expected-line-ending-format = "CRLF"
max-line-length = 72
