[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line_length = 72

[tool.isort]
force_grid_wrap = 2
line_ending="\r\n"
line_length = 72
profile = "black"
remove_redundant_aliases = true

[tool.pylint.main]
disable = "empty-docstring, too-few-public-methods"
# I think this goes here and is right \/
ignored-argument-names="cls|star|self"

[tool.pylint.format]
expected-line-ending-format = "CRLF"
max-line-length = 72

[tool.pyright]
# typeCheckingMode = "strict"
typeCheckingMode = "basic"
