from Unicode.U0000 import NULL
from Unicode.U0000 import START_OF_HEADING
from Unicode.U0000 import START_OF_TEXT
from Unicode.U0000 import END_OF_TEXT
from Unicode.U0000 import END_OF_TRANSMISSION
from Unicode.U0000 import ENQUIRY
from Unicode.U0000 import ACKNOWLEDGE
from Unicode.U0000 import BELL
from Unicode.U0000 import BACKSPACE
from Unicode.U0000 import CHARACTER_TABULATION
from Unicode.U0000 import LINE_FEED
from Unicode.U0000 import LINE_TABULATION
from Unicode.U0000 import FORM_FEED
from Unicode.U0000 import CARRIAGE_RETURN
from Unicode.U0000 import SHIFT_OUT
from Unicode.U0000 import SHIFT_IN
from Unicode.U0000 import DATA_LINK_ESCAPE
from Unicode.U0000 import DEVICE_CONTROL_ONE
from Unicode.U0000 import DEVICE_CONTROL_TWO
from Unicode.U0000 import DEVICE_CONTROL_THREE
from Unicode.U0000 import DEVICE_CONTROL_FOUR
from Unicode.U0000 import NEGATIVE_ACKNOWLEDGE
from Unicode.U0000 import SYNCHRONOUS_IDLE
from Unicode.U0000 import END_OF_TRANSMISSION_BLOCK
from Unicode.U0000 import CANCEL
from Unicode.U0000 import END_OF_MEDIUM
from Unicode.U0000 import SUBSTITUTE
from Unicode.U0000 import ESCAPE
from Unicode.U0000 import INFORMATION_SEPARATOR_FOUR
from Unicode.U0000 import INFORMATION_SEPARATOR_THREE
from Unicode.U0000 import INFORMATION_SEPARATOR_TWO
from Unicode.U0000 import INFORMATION_SEPARATOR_ONE
from Unicode.U0000 import SPACE
from Unicode.U0000 import EXCLAMATION_MARK
from Unicode.U0000 import QUOTATION_MARK
from Unicode.U0000 import NUMBER_SIGN
from Unicode.U0000 import DOLLAR_SIGN
from Unicode.U0000 import PERCENT_SIGN
from Unicode.U0000 import AMPERSAND
from Unicode.U0000 import APOSTROPHE
from Unicode.U0000 import LEFT_PARENTHESIS
from Unicode.U0000 import RIGHT_PARENTHESIS
from Unicode.U0000 import ASTERISK
from Unicode.U0000 import PLUS_SIGN
from Unicode.U0000 import COMMA
from Unicode.U0000 import HYPHEN_MINUS
from Unicode.U0000 import FULL_STOP
from Unicode.U0000 import SOLIDUS
from Unicode.U0000 import DIGIT_ZERO
from Unicode.U0000 import DIGIT_ONE
from Unicode.U0000 import DIGIT_TWO
from Unicode.U0000 import DIGIT_THREE
from Unicode.U0000 import DIGIT_FOUR
from Unicode.U0000 import DIGIT_FIVE
from Unicode.U0000 import DIGIT_SIX
from Unicode.U0000 import DIGIT_SEVEN
from Unicode.U0000 import DIGIT_EIGHT
from Unicode.U0000 import DIGIT_NINE
from Unicode.U0000 import COLON
from Unicode.U0000 import SEMICOLON
from Unicode.U0000 import LESS_THAN_SIGN
from Unicode.U0000 import EQUALS_SIGN
from Unicode.U0000 import GREATER_THAN_SIGN
from Unicode.U0000 import QUESTION_MARK
from Unicode.U0000 import COMMERCIA_AT
from Unicode.U0000 import LATIN_CAPITAL_LETTER_A
from Unicode.U0000 import LATIN_CAPITAL_LETTER_B
from Unicode.U0000 import LATIN_CAPITAL_LETTER_C
from Unicode.U0000 import LATIN_CAPITAL_LETTER_D
from Unicode.U0000 import LATIN_CAPITAL_LETTER_E
from Unicode.U0000 import LATIN_CAPITAL_LETTER_F
from Unicode.U0000 import LATIN_CAPITAL_LETTER_G
from Unicode.U0000 import LATIN_CAPITAL_LETTER_H
from Unicode.U0000 import LATIN_CAPITAL_LETTER_I
from Unicode.U0000 import LATIN_CAPITAL_LETTER_J
from Unicode.U0000 import LATIN_CAPITAL_LETTER_K
from Unicode.U0000 import LATIN_CAPITAL_LETTER_L
from Unicode.U0000 import LATIN_CAPITAL_LETTER_M
from Unicode.U0000 import LATIN_CAPITAL_LETTER_N
from Unicode.U0000 import LATIN_CAPITAL_LETTER_O
from Unicode.U0000 import LATIN_CAPITAL_LETTER_P
from Unicode.U0000 import LATIN_CAPITAL_LETTER_Q
from Unicode.U0000 import LATIN_CAPITAL_LETTER_R
from Unicode.U0000 import LATIN_CAPITAL_LETTER_S
from Unicode.U0000 import LATIN_CAPITAL_LETTER_T
from Unicode.U0000 import LATIN_CAPITAL_LETTER_U
from Unicode.U0000 import LATIN_CAPITAL_LETTER_V
from Unicode.U0000 import LATIN_CAPITAL_LETTER_W
from Unicode.U0000 import LATIN_CAPITAL_LETTER_X
from Unicode.U0000 import LATIN_CAPITAL_LETTER_Y
from Unicode.U0000 import LATIN_CAPITAL_LETTER_Z
from Unicode.U0000 import LEFT_SQUARE_BRACKET
from Unicode.U0000 import REVERSE_SOLIDUS
from Unicode.U0000 import RIGHT_SQUARE_BRACKET
from Unicode.U0000 import CIRCUMFLEX_ACCENT
from Unicode.U0000 import LOW_LINE
from Unicode.U0000 import GRAVE_ACCENT
from Unicode.U0000 import LATIN_SMALL_LETTER_A
from Unicode.U0000 import LATIN_SMALL_LETTER_B
from Unicode.U0000 import LATIN_SMALL_LETTER_C
from Unicode.U0000 import LATIN_SMALL_LETTER_D
from Unicode.U0000 import LATIN_SMALL_LETTER_E
from Unicode.U0000 import LATIN_SMALL_LETTER_F
from Unicode.U0000 import LATIN_SMALL_LETTER_G
from Unicode.U0000 import LATIN_SMALL_LETTER_H
from Unicode.U0000 import LATIN_SMALL_LETTER_I
from Unicode.U0000 import LATIN_SMALL_LETTER_J
from Unicode.U0000 import LATIN_SMALL_LETTER_K
from Unicode.U0000 import LATIN_SMALL_LETTER_L
from Unicode.U0000 import LATIN_SMALL_LETTER_M
from Unicode.U0000 import LATIN_SMALL_LETTER_N
from Unicode.U0000 import LATIN_SMALL_LETTER_O
from Unicode.U0000 import LATIN_SMALL_LETTER_P
from Unicode.U0000 import LATIN_SMALL_LETTER_Q
from Unicode.U0000 import LATIN_SMALL_LETTER_R
from Unicode.U0000 import LATIN_SMALL_LETTER_S
from Unicode.U0000 import LATIN_SMALL_LETTER_T
from Unicode.U0000 import LATIN_SMALL_LETTER_U
from Unicode.U0000 import LATIN_SMALL_LETTER_V
from Unicode.U0000 import LATIN_SMALL_LETTER_W
from Unicode.U0000 import LATIN_SMALL_LETTER_X
from Unicode.U0000 import LATIN_SMALL_LETTER_Y
from Unicode.U0000 import LATIN_SMALL_LETTER_Z
from Unicode.U0000 import LEFT_CURLY_BRACKET
from Unicode.U0000 import VERTICAL_LINE
from Unicode.U0000 import RIGHT_CURLY_BRACKET
from Unicode.U0000 import TILDE
from Unicode.U0000 import DELETE

from Unicode_Encoding.U0000 import C0_CONTROLS_AND_BASIC_LATIN
from Unicode_Encoding.U0080 import C1_CONTROLS_AND_LATIN_1_SUPPLEMENT

from tag.comparison import comparison

convert = C0_CONTROLS_AND_BASIC_LATIN | C1_CONTROLS_AND_LATIN_1_SUPPLEMENT

lowercase = {
    LATIN_CAPITAL_LETTER_A: LATIN_SMALL_LETTER_A,
    LATIN_CAPITAL_LETTER_B: LATIN_SMALL_LETTER_B,
    LATIN_CAPITAL_LETTER_C: LATIN_SMALL_LETTER_C,
    LATIN_CAPITAL_LETTER_D: LATIN_SMALL_LETTER_D,
    LATIN_CAPITAL_LETTER_E: LATIN_SMALL_LETTER_E,
    LATIN_CAPITAL_LETTER_F: LATIN_SMALL_LETTER_F,
    LATIN_CAPITAL_LETTER_G: LATIN_SMALL_LETTER_G,
    LATIN_CAPITAL_LETTER_H: LATIN_SMALL_LETTER_H,
    LATIN_CAPITAL_LETTER_I: LATIN_SMALL_LETTER_I,
    LATIN_CAPITAL_LETTER_J: LATIN_SMALL_LETTER_J,
    LATIN_CAPITAL_LETTER_K: LATIN_SMALL_LETTER_K,
    LATIN_CAPITAL_LETTER_L: LATIN_SMALL_LETTER_L,
    LATIN_CAPITAL_LETTER_M: LATIN_SMALL_LETTER_M,
    LATIN_CAPITAL_LETTER_N: LATIN_SMALL_LETTER_N,
    LATIN_CAPITAL_LETTER_O: LATIN_SMALL_LETTER_O,
    LATIN_CAPITAL_LETTER_P: LATIN_SMALL_LETTER_P,
    LATIN_CAPITAL_LETTER_Q: LATIN_SMALL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R: LATIN_SMALL_LETTER_R,
    LATIN_CAPITAL_LETTER_S: LATIN_SMALL_LETTER_S,
    LATIN_CAPITAL_LETTER_T: LATIN_SMALL_LETTER_T,
    LATIN_CAPITAL_LETTER_U: LATIN_SMALL_LETTER_U,
    LATIN_CAPITAL_LETTER_V: LATIN_SMALL_LETTER_V,
    LATIN_CAPITAL_LETTER_W: LATIN_SMALL_LETTER_W,
    LATIN_CAPITAL_LETTER_X: LATIN_SMALL_LETTER_X,
    LATIN_CAPITAL_LETTER_Y: LATIN_SMALL_LETTER_Y,
    LATIN_CAPITAL_LETTER_Z: LATIN_SMALL_LETTER_Z,
    LOW_LINE: LOW_LINE,
    LATIN_SMALL_LETTER_A: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B: LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C: LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D: LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F: LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G: LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H: LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J: LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K: LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L: LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M: LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N: LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P: LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q: LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R: LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S: LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T: LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V: LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W: LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X: LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y: LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z: LATIN_SMALL_LETTER_Z,
}

number = {
    DIGIT_ZERO,
    DIGIT_ONE,
    DIGIT_TWO,
    DIGIT_THREE,
    DIGIT_FOUR,
    DIGIT_FIVE,
    DIGIT_SIX,
    DIGIT_SEVEN,
    DIGIT_EIGHT,
    DIGIT_NINE,
    LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_D,
    LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F,
}

tag = {
    LOW_LINE,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z
}

space = {
    SPACE
}

sql_and = {
    AMPERSAND
}

sql_is = {
    PLUS_SIGN
}

sql_not = {
    HYPHEN_MINUS
}

sql_or = {
    VERTICAL_LINE
}

logica_operator = sql_and | sql_is | sql_not | sql_or


letter = {
    DIGIT_ZERO,
    DIGIT_ONE,
    DIGIT_TWO,
    DIGIT_THREE,
    DIGIT_FOUR,
    DIGIT_FIVE,
    DIGIT_SIX,
    DIGIT_SEVEN,
    DIGIT_EIGHT,
    DIGIT_NINE,
    LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_D,
    LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F,
    LATIN_CAPITAL_LETTER_G,
    LATIN_CAPITAL_LETTER_H,
    LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_J,
    LATIN_CAPITAL_LETTER_K,
    LATIN_CAPITAL_LETTER_L,
    LATIN_CAPITAL_LETTER_M,
    LATIN_CAPITAL_LETTER_N,
    LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_P,
    LATIN_CAPITAL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R,
    LATIN_CAPITAL_LETTER_S,
    LATIN_CAPITAL_LETTER_T,
    LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_V,
    LATIN_CAPITAL_LETTER_W,
    LATIN_CAPITAL_LETTER_X,
    LATIN_CAPITAL_LETTER_Y,
    LATIN_CAPITAL_LETTER_Z,
    LOW_LINE,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z
}


one_token = {
    QUOTATION_MARK,
    NUMBER_SIGN,
    DOLLAR_SIGN,
    PERCENT_SIGN,
    AMPERSAND,
    APOSTROPHE,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    ASTERISK,
    PLUS_SIGN,
    COMMA,
    HYPHEN_MINUS,
    FULL_STOP,
    SOLIDUS,
    COLON,
    SEMICOLON,
    QUESTION_MARK,
    COMMERCIA_AT,
    LEFT_SQUARE_BRACKET,
    REVERSE_SOLIDUS,
    RIGHT_SQUARE_BRACKET,
    CIRCUMFLEX_ACCENT,
    GRAVE_ACCENT,
    LEFT_CURLY_BRACKET,
    VERTICAL_LINE,
    RIGHT_CURLY_BRACKET,
    TILDE,
}

comparison = {
    EXCLAMATION_MARK,
    LESS_THAN_SIGN,
    EQUALS_SIGN,
    GREATER_THAN_SIGN,
}

logical = {
    AMPERSAND,
    PLUS_SIGN,
    HYPHEN_MINUS,
    CIRCUMFLEX_ACCENT,
    VERTICAL_LINE,
    TILDE
}


digit = {
    DIGIT_ZERO,
    DIGIT_ONE,
    DIGIT_TWO,
    DIGIT_THREE,
    DIGIT_FOUR,
    DIGIT_FIVE,
    DIGIT_SIX,
    DIGIT_SEVEN,
    DIGIT_EIGHT,
    DIGIT_NINE,
}

consonant = {
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Z
}

vowel = {
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_Y
}

wildcard = {
    NUMBER_SIGN,
    PERCENT_SIGN,
    ASTERISK,
    COLON,
    QUESTION_MARK,
    COMMERCIA_AT,
}


# The percent sign % can be used to match a number


# The asterisk (*) matches any number of characters. That means that you can use it as a placeholder for any sequence of letters or symbols. For example, if you enter blueb* you'll get all the terms that start with "blueb"; if you enter *bird you'll get all the terms that end with "bird"; if you enter *lueb* you'll get all the terms that contain the sequence "lueb", and so forth. An asterisk can match zero characters, too.

# The question mark (?) matches exactly one character. That means that you can use it as a placeholder for a single letter or symbol. The query l?b?n?n,  for example, will find the word "Lebanon".

# (NEW!) The number-sign (#) matches any English consonant. For example, the query tra#t finds the word "tract" but not "trait".

# (NEW!) The at-sign (@) matches any English vowel. For example, the query abo@t finds the word "about" but not "abort".

# Filter by meaning: Did you know that you can filter your wildcard searches by meaning? Put a colon (:) after your pattern and then type a word or two describing what you're looking for. For example, the query p*:ireland finds terms beginning with "p" that have something to do with Ireland, and the query *:widespread epidemic searches for terms having something to do with "widespread epidemic". The latter case demonstrates how OneLook.com can be used as a means of finding a word (in this case, pandemic) if you only know its definition. See the reverse dictionary page for more details on this feature.


comparison | logical | digit | consonant | vowel | wildcard

all_token = one_token | letter | comparison | logical
