from mem_dixy.tkinter.Widget import Tk
from U0000 import *


print(BELL)
# print(chr(TILDE))
print(ord(BELL))

print (4 in [1, 2, 3])


bacon = [
    PLUS_SIGN,
    HYPHEN_MINUS,
    DIGIT_ZERO,
    DIGIT_ONE,
    DIGIT_TWO,
    DIGIT_THREE,
    DIGIT_FOUR,
    DIGIT_FIVE,
    DIGIT_SIX,
    DIGIT_SEVEN,
    DIGIT_EIGHT,
    DIGIT_NINE,
    LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_D,
    LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F,
    LATIN_CAPITAL_LETTER_G,
    LATIN_CAPITAL_LETTER_H,
    LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_J,
    LATIN_CAPITAL_LETTER_K,
    LATIN_CAPITAL_LETTER_L,
    LATIN_CAPITAL_LETTER_M,
    LATIN_CAPITAL_LETTER_N,
    LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_P,
    LATIN_CAPITAL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R,
    LATIN_CAPITAL_LETTER_S,
    LATIN_CAPITAL_LETTER_T,
    LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_V,
    LATIN_CAPITAL_LETTER_W,
    LATIN_CAPITAL_LETTER_X,
    LATIN_CAPITAL_LETTER_Y,
    LATIN_CAPITAL_LETTER_Z,
    LOW_LINE,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z
]

print(bacon)
