"""Central place for text strings."""
from celestine.typed import string
from celestine.unicode import (
    FULL_STOP,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_Y,
    LESS_THAN_SIGN,
    LOW_LINE,
    SPACE,
)

INIT = string(
    LOW_LINE,
    LOW_LINE,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_T,
    LOW_LINE,
    LOW_LINE,
)
FUNCTION = string(
    LESS_THAN_SIGN,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
    SPACE,
)
PYTHON_EXTENSION = string(
    FULL_STOP,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Y,
)
#############
APPLICATION = string(
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
)
BLENDER = string(
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
)
CELESTINE = string(
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_E,
)
CONFIGURATION = string(
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
)
DIRECTORY = string(
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_Y,
)
INTERFACE = string(
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_E,
)
LANGUAGE = string(
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_E,
)
PACKAGE = string(
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_E,
)
REGISTER = string(
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
)
UNREGISTER = string(
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
)
VERSION_NUMBER = "2023.10.7"
