"""Central place for text strings."""

from celestine.typed import S
from celestine.unicode import (
    FULL_STOP,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_Y,
    LESS_THAN_SIGN,
    LOW_LINE,
    NONE,
    SPACE,
)


def join(*iterable: S) -> S:
    return NONE.join(iterable)


FUNCTION = join(
    LESS_THAN_SIGN,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
    SPACE,
)
INIT = join(
    LOW_LINE,
    LOW_LINE,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_T,
    LOW_LINE,
    LOW_LINE,
)
PYTHON_EXTENSION = join(
    FULL_STOP,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Y,
)
########################################################################
APPLICATION = join(
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
)
BLENDER = join(
    LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
)
CELESTINE = join(
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_E,
)
CONFIGURATION = join(
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_N,
)
DIRECTORY = join(
    LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_Y,
)
INTERFACE = join(
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_E,
)
LANGUAGE = join(
    LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_E,
)
PACKAGE = join(
    LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_E,
)
REGISTER = join(
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
)
UNREGISTER = join(
    LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_R,
)
########################################################################
VERSION_NUMBER = "2023.10.7"
