from celestine.unicode.u0080 import U0080
from celestine.unicode.u0080 import U0081
from celestine.unicode.u0080 import BREAK_PERMITTED_HERE
from celestine.unicode.u0080 import NO_BREAK_HERE
from celestine.unicode.u0080 import INDEX
from celestine.unicode.u0080 import NEXT_LINE
from celestine.unicode.u0080 import START_OF_SELECTED_AREA
from celestine.unicode.u0080 import END_OF_SELECTED_AREA
from celestine.unicode.u0080 import CHARACTER_TABULATION_SET
from celestine.unicode.u0080 import CHARACTER_TABULATION_WITHJUSTIFICATION
from celestine.unicode.u0080 import LINE_TABULATION_SET
from celestine.unicode.u0080 import PARTIAL_LINE_FORWARD
from celestine.unicode.u0080 import PARTIAL_LINE_BACKWARD
from celestine.unicode.u0080 import REVERSE_LINE_FEED
from celestine.unicode.u0080 import SINGLE_SHIFT_TWO
from celestine.unicode.u0080 import SINGLE_SHIFT_THREE
from celestine.unicode.u0080 import DEVICE_CONTROL_STRING
from celestine.unicode.u0080 import PRIVATE_USE_ONE
from celestine.unicode.u0080 import PRIVATE_USE_TWO
from celestine.unicode.u0080 import SET_TRANSMIT_STATE
from celestine.unicode.u0080 import CANCEL_CHARACTER
from celestine.unicode.u0080 import MESSAGE_WAITING
from celestine.unicode.u0080 import START_OF_GUARDED_AREA
from celestine.unicode.u0080 import END_OF_GUARDED_AREA
from celestine.unicode.u0080 import START_OF_STRING
from celestine.unicode.u0080 import U0099
from celestine.unicode.u0080 import SINGLE_CHARACTER_INTRODUCER
from celestine.unicode.u0080 import CONTROL_SEQUENCE_INTRODUCER
from celestine.unicode.u0080 import STRING_TERMINATOR
from celestine.unicode.u0080 import OPERATING_SYSTEM_COMMAND
from celestine.unicode.u0080 import PRIVACY_MESSAGE
from celestine.unicode.u0080 import APPLICATION_PROGRAM_COMMAND
from celestine.unicode.u0080 import NO_BREAK_SPACE
from celestine.unicode.u0080 import INVERTED_EXCLAMATION_MARK
from celestine.unicode.u0080 import CENT_SIGN
from celestine.unicode.u0080 import POUND_SIGN
from celestine.unicode.u0080 import CURRENCY_SIGN
from celestine.unicode.u0080 import YEN_SIGN
from celestine.unicode.u0080 import BROKEN_BAR
from celestine.unicode.u0080 import SECTION_SIGN
from celestine.unicode.u0080 import DIAERESIS
from celestine.unicode.u0080 import COPYRIGHT_SIGN
from celestine.unicode.u0080 import FEMININE_ORDINAL_INDICATOR
from celestine.unicode.u0080 import LEFT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK
from celestine.unicode.u0080 import NOT_SIGN
from celestine.unicode.u0080 import SOFT_HYPHEN
from celestine.unicode.u0080 import REGISTERED_SIGN
from celestine.unicode.u0080 import MACRON
from celestine.unicode.u0080 import DEGREE_SIGN
from celestine.unicode.u0080 import PLUS_MINUS_SIGN
from celestine.unicode.u0080 import SUPERSCRIPT_TWO
from celestine.unicode.u0080 import SUPERSCRIPT_THREE
from celestine.unicode.u0080 import ACUTE_ACCENT
from celestine.unicode.u0080 import MICRO_SIGN
from celestine.unicode.u0080 import PILCROW_SIGN
from celestine.unicode.u0080 import MIDDLE_DOT
from celestine.unicode.u0080 import CEDILLA
from celestine.unicode.u0080 import SUPERSCRIPT_ONE
from celestine.unicode.u0080 import MASCULINE_ORDINAL_INDICATOR
from celestine.unicode.u0080 import RIGHT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK
from celestine.unicode.u0080 import VULGAR_FRACTION_ONE_QUARTER
from celestine.unicode.u0080 import VULGAR_FRACTION_ONE_HALF
from celestine.unicode.u0080 import VULGAR_FRACTION_THREE_QUARTERS
from celestine.unicode.u0080 import INVERTED_QUESTION_MARK
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_A_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_A_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_A_WITH_TILDE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_AE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_C_WITH_CEDILLA
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_E_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_E_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_I_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_I_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_ETH
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_N_WITH_TILDE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_O_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_O_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_O_WITH_TILDE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS
from celestine.unicode.u0080 import MULTIPLICATION_SIGN
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_O_WITH_STROKE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_U_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_U_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_Y_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_CAPITAL_LETTER_THORN
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_SHARP_S
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_A_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_A_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_A_WITH_TILDE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_A_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_A_WITH_RING_ABOVE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_AE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_C_WITH_CEDILLA
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_E_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_E_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_E_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_I_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_I_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_I_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_ETH
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_N_WITH_TILDE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_O_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_O_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_O_WITH_TILDE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_O_WITH_DIAERESIS
from celestine.unicode.u0080 import DIVISION_SIGN
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_O_WITH_STROKE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_U_WITH_GRAVE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_U_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_U_WITH_DIAERESIS
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_Y_WITH_ACUTE
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_THORN
from celestine.unicode.u0080 import LATIN_SMALL_LETTER_Y_WITH_DIAERESIS

from celestine.alphabet import NONE
from celestine.alphabet import WHITESPACE
from celestine.alphabet import SIGN_MARK
from celestine.alphabet import SIGN_STAR
from celestine.alphabet import SIGN_DASH
from celestine.alphabet import LETTER_A
from celestine.alphabet import LETTER_C
from celestine.alphabet import LETTER_E
from celestine.alphabet import LETTER_I
from celestine.alphabet import LETTER_N
from celestine.alphabet import LETTER_O
from celestine.alphabet import LETTER_U
from celestine.alphabet import LETTER_Y

u0080 = {
    U0080: NONE,
    U0081: NONE,
    BREAK_PERMITTED_HERE: NONE,
    NO_BREAK_HERE: NONE,
    INDEX: NONE,
    NEXT_LINE: NONE,
    START_OF_SELECTED_AREA: NONE,
    END_OF_SELECTED_AREA: NONE,
    CHARACTER_TABULATION_SET: NONE,
    CHARACTER_TABULATION_WITHJUSTIFICATION: NONE,
    LINE_TABULATION_SET: NONE,
    PARTIAL_LINE_FORWARD: NONE,
    PARTIAL_LINE_BACKWARD: NONE,
    REVERSE_LINE_FEED: NONE,
    SINGLE_SHIFT_TWO: NONE,
    SINGLE_SHIFT_THREE: NONE,
    DEVICE_CONTROL_STRING: NONE,
    PRIVATE_USE_ONE: NONE,
    PRIVATE_USE_TWO: NONE,
    SET_TRANSMIT_STATE: NONE,
    CANCEL_CHARACTER: NONE,
    MESSAGE_WAITING: NONE,
    START_OF_GUARDED_AREA: NONE,
    END_OF_GUARDED_AREA: NONE,
    START_OF_STRING: NONE,
    U0099: NONE,
    SINGLE_CHARACTER_INTRODUCER: NONE,
    CONTROL_SEQUENCE_INTRODUCER: NONE,
    STRING_TERMINATOR: NONE,
    OPERATING_SYSTEM_COMMAND: NONE,
    PRIVACY_MESSAGE: NONE,
    APPLICATION_PROGRAM_COMMAND: NONE,
    NO_BREAK_SPACE: WHITESPACE,
    INVERTED_EXCLAMATION_MARK: SIGN_MARK,
    CENT_SIGN: NONE,
    POUND_SIGN: NONE,
    CURRENCY_SIGN: NONE,
    YEN_SIGN: NONE,
    BROKEN_BAR: NONE,
    SECTION_SIGN: NONE,
    DIAERESIS: NONE,
    COPYRIGHT_SIGN: NONE,
    FEMININE_ORDINAL_INDICATOR: NONE,
    LEFT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK: NONE,
    NOT_SIGN: NONE,
    SOFT_HYPHEN: SIGN_DASH,
    REGISTERED_SIGN: NONE,
    MACRON: NONE,
    DEGREE_SIGN: NONE,
    PLUS_MINUS_SIGN: NONE,
    SUPERSCRIPT_TWO: NONE,
    SUPERSCRIPT_THREE: NONE,
    ACUTE_ACCENT: NONE,
    MICRO_SIGN: NONE,
    PILCROW_SIGN: NONE,
    MIDDLE_DOT: NONE,
    CEDILLA: NONE,
    SUPERSCRIPT_ONE: NONE,
    MASCULINE_ORDINAL_INDICATOR: NONE,
    RIGHT_POINTING_DOUBLE_ANGLE_QUOTATIONMARK: NONE,
    VULGAR_FRACTION_ONE_QUARTER: NONE,
    VULGAR_FRACTION_ONE_HALF: NONE,
    VULGAR_FRACTION_THREE_QUARTERS: NONE,
    INVERTED_QUESTION_MARK: NONE,
    LATIN_CAPITAL_LETTER_A_WITH_GRAVE: LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_ACUTE: LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX: LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_TILDE: LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS: LETTER_A,
    LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE: LETTER_A,
    LATIN_CAPITAL_LETTER_AE: NONE,
    LATIN_CAPITAL_LETTER_C_WITH_CEDILLA: LETTER_C,
    LATIN_CAPITAL_LETTER_E_WITH_GRAVE: LETTER_E,
    LATIN_CAPITAL_LETTER_E_WITH_ACUTE: LETTER_E,
    LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX: LETTER_E,
    LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS: LETTER_E,
    LATIN_CAPITAL_LETTER_I_WITH_GRAVE: LETTER_I,
    LATIN_CAPITAL_LETTER_I_WITH_ACUTE: LETTER_I,
    LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX: LETTER_I,
    LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS: LETTER_I,
    LATIN_CAPITAL_LETTER_ETH: NONE,
    LATIN_CAPITAL_LETTER_N_WITH_TILDE: LETTER_N,
    LATIN_CAPITAL_LETTER_O_WITH_GRAVE: LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_ACUTE: LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX: LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_TILDE: LETTER_O,
    LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS: LETTER_O,
    MULTIPLICATION_SIGN: SIGN_STAR,
    LATIN_CAPITAL_LETTER_O_WITH_STROKE: LETTER_O,
    LATIN_CAPITAL_LETTER_U_WITH_GRAVE: LETTER_U,
    LATIN_CAPITAL_LETTER_U_WITH_ACUTE: LETTER_U,
    LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX: LETTER_U,
    LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS: LETTER_U,
    LATIN_CAPITAL_LETTER_Y_WITH_ACUTE: LETTER_Y,
    LATIN_CAPITAL_LETTER_THORN: NONE,
    LATIN_SMALL_LETTER_SHARP_S: NONE,
    LATIN_SMALL_LETTER_A_WITH_GRAVE: LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_ACUTE: LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX: LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_TILDE: LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_DIAERESIS: LETTER_A,
    LATIN_SMALL_LETTER_A_WITH_RING_ABOVE: LETTER_A,
    LATIN_SMALL_LETTER_AE: NONE,
    LATIN_SMALL_LETTER_C_WITH_CEDILLA: LETTER_C,
    LATIN_SMALL_LETTER_E_WITH_GRAVE: LETTER_E,
    LATIN_SMALL_LETTER_E_WITH_ACUTE: LETTER_E,
    LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX: LETTER_E,
    LATIN_SMALL_LETTER_E_WITH_DIAERESIS: LETTER_E,
    LATIN_SMALL_LETTER_I_WITH_GRAVE: LETTER_I,
    LATIN_SMALL_LETTER_I_WITH_ACUTE: LETTER_I,
    LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX: LETTER_I,
    LATIN_SMALL_LETTER_I_WITH_DIAERESIS: LETTER_I,
    LATIN_SMALL_LETTER_ETH: NONE,
    LATIN_SMALL_LETTER_N_WITH_TILDE: LETTER_N,
    LATIN_SMALL_LETTER_O_WITH_GRAVE: LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_ACUTE: LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX: LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_TILDE: LETTER_O,
    LATIN_SMALL_LETTER_O_WITH_DIAERESIS: LETTER_O,
    DIVISION_SIGN: NONE,
    LATIN_SMALL_LETTER_O_WITH_STROKE: LETTER_O,
    LATIN_SMALL_LETTER_U_WITH_GRAVE: LETTER_U,
    LATIN_SMALL_LETTER_U_WITH_ACUTE: LETTER_U,
    LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX: LETTER_U,
    LATIN_SMALL_LETTER_U_WITH_DIAERESIS: LETTER_U,
    LATIN_SMALL_LETTER_Y_WITH_ACUTE: LETTER_Y,
    LATIN_SMALL_LETTER_THORN: NONE,
    LATIN_SMALL_LETTER_Y_WITH_DIAERESIS: LETTER_U
}
