from celestine.unicode.u2700 import BLACK_SAFETY_SCISSORS
from celestine.unicode.u2700 import UPPER_BLADE_SCISSORS
from celestine.unicode.u2700 import BLACK_SCISSORS
from celestine.unicode.u2700 import LOWER_BLADE_SCISSORS
from celestine.unicode.u2700 import WHITE_SCISSORS
from celestine.unicode.u2700 import WHITE_HEAVY_CHECK_MARK
from celestine.unicode.u2700 import TELEPHONE_LOCATION_SIGN
from celestine.unicode.u2700 import TAPE_DRIVE
from celestine.unicode.u2700 import AIRPLANE
from celestine.unicode.u2700 import ENVELOPE
from celestine.unicode.u2700 import RAISED_FIST
from celestine.unicode.u2700 import RAISED_HAND
from celestine.unicode.u2700 import VICTORY_HAND
from celestine.unicode.u2700 import WRITING_HAND
from celestine.unicode.u2700 import LOWER_RIGHT_PENCIL
from celestine.unicode.u2700 import PENCIL
from celestine.unicode.u2700 import UPPER_RIGHT_PENCIL
from celestine.unicode.u2700 import WHITE_NIB
from celestine.unicode.u2700 import BLACK_NIB
from celestine.unicode.u2700 import CHECK_MARK
from celestine.unicode.u2700 import HEAVY_CHECK_MARK
from celestine.unicode.u2700 import MULTIPLICATION_X
from celestine.unicode.u2700 import HEAVY_MULTIPLICATION_X
from celestine.unicode.u2700 import BALLOT_X
from celestine.unicode.u2700 import HEAVY_BALLOT_X
from celestine.unicode.u2700 import OUTLINED_GREEK_CROSS
from celestine.unicode.u2700 import HEAVY_GREEK_CROSS
from celestine.unicode.u2700 import OPEN_CENTRE_CROSS
from celestine.unicode.u2700 import HEAVY_OPEN_CENTRE_CROSS
from celestine.unicode.u2700 import LATIN_CROSS
from celestine.unicode.u2700 import SHADOWED_WHITE_LATIN_CROSS
from celestine.unicode.u2700 import OUTLINED_LATIN_CROSS
from celestine.unicode.u2700 import MALTESE_CROSS
from celestine.unicode.u2700 import STAR_OF_DAVID
from celestine.unicode.u2700 import FOUR_TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import FOUR_BALLOON_SPOKED_ASTERISK
from celestine.unicode.u2700 import HEAVY_FOUR_BALLOON_SPOKED_ASTERISK
from celestine.unicode.u2700 import FOUR_CLUB_SPOKED_ASTERISK
from celestine.unicode.u2700 import BLACK_FOUR_POINTED_STAR
from celestine.unicode.u2700 import WHITE_FOUR_POINTED_STAR
from celestine.unicode.u2700 import SPARKLES
from celestine.unicode.u2700 import STRESS_OUTLINED_WHITE_STAR
from celestine.unicode.u2700 import CIRCLED_WHITE_STAR
from celestine.unicode.u2700 import OPEN_CENTRE_BLACK_STAR
from celestine.unicode.u2700 import BLACK_CENTRE_WHITE_STAR
from celestine.unicode.u2700 import OUTLINED_BLACK_STAR
from celestine.unicode.u2700 import HEAVY_OUTLINED_BLACK_STAR
from celestine.unicode.u2700 import PINWHEEL_STAR
from celestine.unicode.u2700 import SHADOWED_WHITE_STAR
from celestine.unicode.u2700 import HEAVY_ASTERISK
from celestine.unicode.u2700 import OPEN_CENTRE_ASTERISK
from celestine.unicode.u2700 import EIGHT_SPOKED_ASTERISK
from celestine.unicode.u2700 import EIGHT_POINTED_BLACK_STAR
from celestine.unicode.u2700 import EIGHT_POINTED_PINWHEEL_STAR
from celestine.unicode.u2700 import SIX_POINTED_BLACK_STAR
from celestine.unicode.u2700 import EIGHT_POINTED_RECTILINEAR_BLACK_STAR
from celestine.unicode.u2700 import HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR
from celestine.unicode.u2700 import TWELVE_POINTED_BLACK_STAR
from celestine.unicode.u2700 import SIXTEEN_POINTED_ASTERISK
from celestine.unicode.u2700 import TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import HEAVY_TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import SIX_PETALLED_BLACK_AND_WHITE_FLORETTE
from celestine.unicode.u2700 import BLACK_FLORETTE
from celestine.unicode.u2700 import WHITE_FLORETTE
from celestine.unicode.u2700 import EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE
from celestine.unicode.u2700 import CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR
from celestine.unicode.u2700 import HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK
from celestine.unicode.u2700 import SNOWFLAKE
from celestine.unicode.u2700 import TIGHT_TRIFOLIATE_SNOWFLAKE
from celestine.unicode.u2700 import HEAVY_CHEVRON_SNOWFLAKE
from celestine.unicode.u2700 import SPARKLE
from celestine.unicode.u2700 import HEAVY_SPARKLE
from celestine.unicode.u2700 import BALLOON_SPOKED_ASTERISK
from celestine.unicode.u2700 import EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK
from celestine.unicode.u2700 import HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK
from celestine.unicode.u2700 import CROSS_MARK
from celestine.unicode.u2700 import SHADOWED_WHITE_CIRCLE
from celestine.unicode.u2700 import NEGATIVE_SQUARED_CROSS_MARK
from celestine.unicode.u2700 import LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import LOWER_RIGHT_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import UPPER_RIGHT_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import BLACK_QUESTION_MARK_ORNAMENT
from celestine.unicode.u2700 import WHITE_QUESTION_MARK_ORNAMENT
from celestine.unicode.u2700 import WHITE_EXCLAMATION_MARK_ORNAMENT
from celestine.unicode.u2700 import BLACK_DIAMOND_MINUS_WHITE_X
from celestine.unicode.u2700 import HEAVY_EXCLAMATION_MARK_SYMBOL
from celestine.unicode.u2700 import LIGHT_VERTICAL_BAR
from celestine.unicode.u2700 import MEDIUM_VERTICAL_BAR
from celestine.unicode.u2700 import HEAVY_VERTICAL_BAR
from celestine.unicode.u2700 import HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LOW_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LOW_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT
from celestine.unicode.u2700 import HEAVY_EXCLAMATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_BLACK_HEART
from celestine.unicode.u2700 import ROTATED_HEAVY_BLACK_HEART_BULLET
from celestine.unicode.u2700 import FLORAL_HEART
from celestine.unicode.u2700 import ROTATED_FLORAL_HEART_BULLET
from celestine.unicode.u2700 import MEDIUM_LEFT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_RIGHT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT
from celestine.unicode.u2700 import LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN
from celestine.unicode.u2700 import HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_PLUS_SIGN
from celestine.unicode.u2700 import HEAVY_MINUS_SIGN
from celestine.unicode.u2700 import HEAVY_DIVISION_SIGN
from celestine.unicode.u2700 import HEAVY_SOUTH_EAST_ARROW
from celestine.unicode.u2700 import HEAVY_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_NORTH_EAST_ARROW
from celestine.unicode.u2700 import DRAFTING_POINT_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BLACK_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD
from celestine.unicode.u2700 import THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD
from celestine.unicode.u2700 import BLACK_RIGHTWARDS_ARROWHEAD
from celestine.unicode.u2700 import HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import SQUAT_BLACK_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import LEFT_SHADED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import CURLY_LOOP
from celestine.unicode.u2700 import NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import WHITE_FEATHERED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BLACK_FEATHERED_SOUTH_EAST_ARROW
from celestine.unicode.u2700 import BLACK_FEATHERED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BLACK_FEATHERED_NORTH_EAST_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW
from celestine.unicode.u2700 import TEARDROP_BARBED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import WEDGE_TAILED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import OPEN_OUTLINED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import DOUBLE_CURLY_LOOP

from celestine.alphabet import NONE
from celestine.alphabet import SIGN_MARK
from celestine.alphabet import SIGN_STAR
from celestine.alphabet import SIGN_PLUS
from celestine.alphabet import SIGN_DASH
from celestine.alphabet import SIGN_LESS
from celestine.alphabet import SIGN_MORE
from celestine.alphabet import DIGIT_1
from celestine.alphabet import DIGIT_2
from celestine.alphabet import DIGIT_3
from celestine.alphabet import DIGIT_4
from celestine.alphabet import DIGIT_5
from celestine.alphabet import DIGIT_6
from celestine.alphabet import DIGIT_7
from celestine.alphabet import DIGIT_8
from celestine.alphabet import DIGIT_9
from celestine.alphabet import DIGIT_A

u2700 = {
    BLACK_SAFETY_SCISSORS: NONE,
    UPPER_BLADE_SCISSORS: NONE,
    BLACK_SCISSORS: NONE,
    LOWER_BLADE_SCISSORS: NONE,
    WHITE_SCISSORS: NONE,
    WHITE_HEAVY_CHECK_MARK: NONE,
    TELEPHONE_LOCATION_SIGN: NONE,
    TAPE_DRIVE: NONE,
    AIRPLANE: NONE,
    ENVELOPE: NONE,
    RAISED_FIST: NONE,
    RAISED_HAND: NONE,
    VICTORY_HAND: NONE,
    WRITING_HAND: NONE,
    LOWER_RIGHT_PENCIL: NONE,
    PENCIL: NONE,
    UPPER_RIGHT_PENCIL: NONE,
    WHITE_NIB: NONE,
    BLACK_NIB: NONE,
    CHECK_MARK: NONE,
    HEAVY_CHECK_MARK: NONE,
    MULTIPLICATION_X: SIGN_STAR,
    HEAVY_MULTIPLICATION_X: SIGN_STAR,
    BALLOT_X: NONE,
    HEAVY_BALLOT_X: NONE,
    OUTLINED_GREEK_CROSS: NONE,
    HEAVY_GREEK_CROSS: NONE,
    OPEN_CENTRE_CROSS: NONE,
    HEAVY_OPEN_CENTRE_CROSS: NONE,
    LATIN_CROSS: NONE,
    SHADOWED_WHITE_LATIN_CROSS: NONE,
    OUTLINED_LATIN_CROSS: NONE,
    MALTESE_CROSS: NONE,
    STAR_OF_DAVID: NONE,
    FOUR_TEARDROP_SPOKED_ASTERISK: NONE,
    FOUR_BALLOON_SPOKED_ASTERISK: NONE,
    HEAVY_FOUR_BALLOON_SPOKED_ASTERISK: NONE,
    FOUR_CLUB_SPOKED_ASTERISK: NONE,
    BLACK_FOUR_POINTED_STAR: NONE,
    WHITE_FOUR_POINTED_STAR: NONE,
    SPARKLES: NONE,
    STRESS_OUTLINED_WHITE_STAR: NONE,
    CIRCLED_WHITE_STAR: NONE,
    OPEN_CENTRE_BLACK_STAR: NONE,
    BLACK_CENTRE_WHITE_STAR: NONE,
    OUTLINED_BLACK_STAR: NONE,
    HEAVY_OUTLINED_BLACK_STAR: NONE,
    PINWHEEL_STAR: NONE,
    SHADOWED_WHITE_STAR: NONE,
    HEAVY_ASTERISK: NONE,
    OPEN_CENTRE_ASTERISK: NONE,
    EIGHT_SPOKED_ASTERISK: NONE,
    EIGHT_POINTED_BLACK_STAR: NONE,
    EIGHT_POINTED_PINWHEEL_STAR: NONE,
    SIX_POINTED_BLACK_STAR: NONE,
    EIGHT_POINTED_RECTILINEAR_BLACK_STAR: NONE,
    HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR: NONE,
    TWELVE_POINTED_BLACK_STAR: NONE,
    SIXTEEN_POINTED_ASTERISK: NONE,
    TEARDROP_SPOKED_ASTERISK: NONE,
    OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK: NONE,
    HEAVY_TEARDROP_SPOKED_ASTERISK: NONE,
    SIX_PETALLED_BLACK_AND_WHITE_FLORETTE: NONE,
    BLACK_FLORETTE: NONE,
    WHITE_FLORETTE: NONE,
    EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE: NONE,
    CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR: NONE,
    HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK: NONE,
    SNOWFLAKE: NONE,
    TIGHT_TRIFOLIATE_SNOWFLAKE: NONE,
    HEAVY_CHEVRON_SNOWFLAKE: NONE,
    SPARKLE: NONE,
    HEAVY_SPARKLE: NONE,
    BALLOON_SPOKED_ASTERISK: NONE,
    EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK: NONE,
    HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK: NONE,
    CROSS_MARK: SIGN_STAR,
    SHADOWED_WHITE_CIRCLE: NONE,
    NEGATIVE_SQUARED_CROSS_MARK: NONE,
    LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE: NONE,
    UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE: NONE,
    LOWER_RIGHT_SHADOWED_WHITE_SQUARE: NONE,
    UPPER_RIGHT_SHADOWED_WHITE_SQUARE: NONE,
    BLACK_QUESTION_MARK_ORNAMENT: NONE,
    WHITE_QUESTION_MARK_ORNAMENT: NONE,
    WHITE_EXCLAMATION_MARK_ORNAMENT: SIGN_MARK,
    BLACK_DIAMOND_MINUS_WHITE_X: NONE,
    HEAVY_EXCLAMATION_MARK_SYMBOL: NONE,
    LIGHT_VERTICAL_BAR: NONE,
    MEDIUM_VERTICAL_BAR: NONE,
    HEAVY_VERTICAL_BAR: NONE,
    HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_LOW_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_LOW_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT: NONE,
    CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT: NONE,
    HEAVY_EXCLAMATION_MARK_ORNAMENT: SIGN_MARK,
    HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT: SIGN_MARK,
    HEAVY_BLACK_HEART: NONE,
    ROTATED_HEAVY_BLACK_HEART_BULLET: NONE,
    FLORAL_HEART: NONE,
    ROTATED_FLORAL_HEART_BULLET: NONE,
    MEDIUM_LEFT_PARENTHESIS_ORNAMENT: NONE,
    MEDIUM_RIGHT_PARENTHESIS_ORNAMENT: NONE,
    MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT: NONE,
    MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT: NONE,
    MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT: SIGN_LESS,
    MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT: SIGN_MORE,
    HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT: NONE,
    HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT: SIGN_LESS,
    HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT: SIGN_MORE,
    LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT: NONE,
    LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT: NONE,
    MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT: NONE,
    MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT: NONE,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE: DIGIT_1,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO: DIGIT_2,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE: DIGIT_3,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR: DIGIT_4,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE: DIGIT_5,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX: DIGIT_6,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN: DIGIT_7,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT: DIGIT_8,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE: DIGIT_9,
    DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN: DIGIT_A,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE: DIGIT_1,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO: DIGIT_2,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE: DIGIT_3,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR: DIGIT_4,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE: DIGIT_5,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX: DIGIT_6,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN: DIGIT_7,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT: DIGIT_8,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE: DIGIT_9,
    DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN: DIGIT_A,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE: DIGIT_1,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO: DIGIT_2,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE: DIGIT_3,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR: DIGIT_4,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE: DIGIT_5,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX: DIGIT_6,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN: DIGIT_7,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT: DIGIT_8,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE: DIGIT_9,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN: DIGIT_A,
    HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW: NONE,
    HEAVY_PLUS_SIGN: SIGN_PLUS,
    HEAVY_MINUS_SIGN: SIGN_DASH,
    HEAVY_DIVISION_SIGN: NONE,
    HEAVY_SOUTH_EAST_ARROW: NONE,
    HEAVY_RIGHTWARDS_ARROW: NONE,
    HEAVY_NORTH_EAST_ARROW: NONE,
    DRAFTING_POINT_RIGHTWARDS_ARROW: NONE,
    HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW: NONE,
    TRIANGLE_HEADED_RIGHTWARDS_ARROW: NONE,
    HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW: NONE,
    DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW: NONE,
    HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW: NONE,
    BLACK_RIGHTWARDS_ARROW: NONE,
    THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD: NONE,
    THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD: NONE,
    BLACK_RIGHTWARDS_ARROWHEAD: NONE,
    HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW: NONE,
    HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW: NONE,
    SQUAT_BLACK_RIGHTWARDS_ARROW: NONE,
    HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW: NONE,
    RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW: NONE,
    LEFT_SHADED_WHITE_RIGHTWARDS_ARROW: NONE,
    BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW: NONE,
    FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW: NONE,
    HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: NONE,
    HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: NONE,
    NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: NONE,
    CURLY_LOOP: NONE,
    NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: NONE,
    CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW: NONE,
    WHITE_FEATHERED_RIGHTWARDS_ARROW: NONE,
    BLACK_FEATHERED_SOUTH_EAST_ARROW: NONE,
    BLACK_FEATHERED_RIGHTWARDS_ARROW: NONE,
    BLACK_FEATHERED_NORTH_EAST_ARROW: NONE,
    HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW: NONE,
    HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW: NONE,
    HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW: NONE,
    TEARDROP_BARBED_RIGHTWARDS_ARROW: NONE,
    HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW: NONE,
    WEDGE_TAILED_RIGHTWARDS_ARROW: NONE,
    HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW: NONE,
    OPEN_OUTLINED_RIGHTWARDS_ARROW: NONE,
    DOUBLE_CURLY_LOOP: NONE
}
