from celestine.unicode.u2700 import BLACK_SAFETY_SCISSORS
from celestine.unicode.u2700 import UPPER_BLADE_SCISSORS
from celestine.unicode.u2700 import BLACK_SCISSORS
from celestine.unicode.u2700 import LOWER_BLADE_SCISSORS
from celestine.unicode.u2700 import WHITE_SCISSORS
from celestine.unicode.u2700 import WHITE_HEAVY_CHECK_MARK
from celestine.unicode.u2700 import TELEPHONE_LOCATION_SIGN
from celestine.unicode.u2700 import TAPE_DRIVE
from celestine.unicode.u2700 import AIRPLANE
from celestine.unicode.u2700 import ENVELOPE
from celestine.unicode.u2700 import RAISED_FIST
from celestine.unicode.u2700 import RAISED_HAND
from celestine.unicode.u2700 import VICTORY_HAND
from celestine.unicode.u2700 import WRITING_HAND
from celestine.unicode.u2700 import LOWER_RIGHT_PENCIL
from celestine.unicode.u2700 import PENCIL
from celestine.unicode.u2700 import UPPER_RIGHT_PENCIL
from celestine.unicode.u2700 import WHITE_NIB
from celestine.unicode.u2700 import BLACK_NIB
from celestine.unicode.u2700 import CHECK_MARK
from celestine.unicode.u2700 import HEAVY_CHECK_MARK
from celestine.unicode.u2700 import MULTIPLICATION_X
from celestine.unicode.u2700 import HEAVY_MULTIPLICATION_X
from celestine.unicode.u2700 import BALLOT_X
from celestine.unicode.u2700 import HEAVY_BALLOT_X
from celestine.unicode.u2700 import OUTLINED_GREEK_CROSS
from celestine.unicode.u2700 import HEAVY_GREEK_CROSS
from celestine.unicode.u2700 import OPEN_CENTRE_CROSS
from celestine.unicode.u2700 import HEAVY_OPEN_CENTRE_CROSS
from celestine.unicode.u2700 import LATIN_CROSS
from celestine.unicode.u2700 import SHADOWED_WHITE_LATIN_CROSS
from celestine.unicode.u2700 import OUTLINED_LATIN_CROSS
from celestine.unicode.u2700 import MALTESE_CROSS
from celestine.unicode.u2700 import STAR_OF_DAVID
from celestine.unicode.u2700 import FOUR_TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import FOUR_BALLOON_SPOKED_ASTERISK
from celestine.unicode.u2700 import HEAVY_FOUR_BALLOON_SPOKED_ASTERISK
from celestine.unicode.u2700 import FOUR_CLUB_SPOKED_ASTERISK
from celestine.unicode.u2700 import BLACK_FOUR_POINTED_STAR
from celestine.unicode.u2700 import WHITE_FOUR_POINTED_STAR
from celestine.unicode.u2700 import SPARKLES
from celestine.unicode.u2700 import STRESS_OUTLINED_WHITE_STAR
from celestine.unicode.u2700 import CIRCLED_WHITE_STAR
from celestine.unicode.u2700 import OPEN_CENTRE_BLACK_STAR
from celestine.unicode.u2700 import BLACK_CENTRE_WHITE_STAR
from celestine.unicode.u2700 import OUTLINED_BLACK_STAR
from celestine.unicode.u2700 import HEAVY_OUTLINED_BLACK_STAR
from celestine.unicode.u2700 import PINWHEEL_STAR
from celestine.unicode.u2700 import SHADOWED_WHITE_STAR
from celestine.unicode.u2700 import HEAVY_ASTERISK
from celestine.unicode.u2700 import OPEN_CENTRE_ASTERISK
from celestine.unicode.u2700 import EIGHT_SPOKED_ASTERISK
from celestine.unicode.u2700 import EIGHT_POINTED_BLACK_STAR
from celestine.unicode.u2700 import EIGHT_POINTED_PINWHEEL_STAR
from celestine.unicode.u2700 import SIX_POINTED_BLACK_STAR
from celestine.unicode.u2700 import EIGHT_POINTED_RECTILINEAR_BLACK_STAR
from celestine.unicode.u2700 import HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR
from celestine.unicode.u2700 import TWELVE_POINTED_BLACK_STAR
from celestine.unicode.u2700 import SIXTEEN_POINTED_ASTERISK
from celestine.unicode.u2700 import TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import HEAVY_TEARDROP_SPOKED_ASTERISK
from celestine.unicode.u2700 import SIX_PETALLED_BLACK_AND_WHITE_FLORETTE
from celestine.unicode.u2700 import BLACK_FLORETTE
from celestine.unicode.u2700 import WHITE_FLORETTE
from celestine.unicode.u2700 import EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE
from celestine.unicode.u2700 import CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR
from celestine.unicode.u2700 import HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK
from celestine.unicode.u2700 import SNOWFLAKE
from celestine.unicode.u2700 import TIGHT_TRIFOLIATE_SNOWFLAKE
from celestine.unicode.u2700 import HEAVY_CHEVRON_SNOWFLAKE
from celestine.unicode.u2700 import SPARKLE
from celestine.unicode.u2700 import HEAVY_SPARKLE
from celestine.unicode.u2700 import BALLOON_SPOKED_ASTERISK
from celestine.unicode.u2700 import EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK
from celestine.unicode.u2700 import HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK
from celestine.unicode.u2700 import CROSS_MARK
from celestine.unicode.u2700 import SHADOWED_WHITE_CIRCLE
from celestine.unicode.u2700 import NEGATIVE_SQUARED_CROSS_MARK
from celestine.unicode.u2700 import LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import LOWER_RIGHT_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import UPPER_RIGHT_SHADOWED_WHITE_SQUARE
from celestine.unicode.u2700 import BLACK_QUESTION_MARK_ORNAMENT
from celestine.unicode.u2700 import WHITE_QUESTION_MARK_ORNAMENT
from celestine.unicode.u2700 import WHITE_EXCLAMATION_MARK_ORNAMENT
from celestine.unicode.u2700 import BLACK_DIAMOND_MINUS_WHITE_X
from celestine.unicode.u2700 import HEAVY_EXCLAMATION_MARK_SYMBOL
from celestine.unicode.u2700 import LIGHT_VERTICAL_BAR
from celestine.unicode.u2700 import MEDIUM_VERTICAL_BAR
from celestine.unicode.u2700 import HEAVY_VERTICAL_BAR
from celestine.unicode.u2700 import HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LOW_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LOW_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT
from celestine.unicode.u2700 import HEAVY_EXCLAMATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_BLACK_HEART
from celestine.unicode.u2700 import ROTATED_HEAVY_BLACK_HEART_BULLET
from celestine.unicode.u2700 import FLORAL_HEART
from celestine.unicode.u2700 import ROTATED_FLORAL_HEART_BULLET
from celestine.unicode.u2700 import MEDIUM_LEFT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_RIGHT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT
from celestine.unicode.u2700 import HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT
from celestine.unicode.u2700 import LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT
from celestine.unicode.u2700 import LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT
from celestine.unicode.u2700 import MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE
from celestine.unicode.u2700 import DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE
from celestine.unicode.u2700 import DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN
from celestine.unicode.u2700 import HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_PLUS_SIGN
from celestine.unicode.u2700 import HEAVY_MINUS_SIGN
from celestine.unicode.u2700 import HEAVY_DIVISION_SIGN
from celestine.unicode.u2700 import HEAVY_SOUTH_EAST_ARROW
from celestine.unicode.u2700 import HEAVY_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_NORTH_EAST_ARROW
from celestine.unicode.u2700 import DRAFTING_POINT_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BLACK_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD
from celestine.unicode.u2700 import THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD
from celestine.unicode.u2700 import BLACK_RIGHTWARDS_ARROWHEAD
from celestine.unicode.u2700 import HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import SQUAT_BLACK_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import LEFT_SHADED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import CURLY_LOOP
from celestine.unicode.u2700 import NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import WHITE_FEATHERED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BLACK_FEATHERED_SOUTH_EAST_ARROW
from celestine.unicode.u2700 import BLACK_FEATHERED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import BLACK_FEATHERED_NORTH_EAST_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW
from celestine.unicode.u2700 import TEARDROP_BARBED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import WEDGE_TAILED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import OPEN_OUTLINED_RIGHTWARDS_ARROW
from celestine.unicode.u2700 import DOUBLE_CURLY_LOOP

from celestine.unicode.u0000 import EXCLAMATION_MARK
from celestine.unicode.u0000 import QUOTATION_MARK
from celestine.unicode.u0000 import APOSTROPHE
from celestine.unicode.u0000 import ASTERISK
from celestine.unicode.u0000 import PLUS_SIGN
from celestine.unicode.u0000 import HYPHEN_MINUS
from celestine.unicode.u0000 import SOLIDUS
from celestine.unicode.u0000 import DIGIT_ZERO
from celestine.unicode.u0000 import DIGIT_ONE
from celestine.unicode.u0000 import DIGIT_TWO
from celestine.unicode.u0000 import DIGIT_THREE
from celestine.unicode.u0000 import DIGIT_FOUR
from celestine.unicode.u0000 import DIGIT_FIVE
from celestine.unicode.u0000 import DIGIT_SIX
from celestine.unicode.u0000 import DIGIT_SEVEN
from celestine.unicode.u0000 import DIGIT_EIGHT
from celestine.unicode.u0000 import DIGIT_NINE
from celestine.unicode.u0000 import LESS_THAN_SIGN
from celestine.unicode.u0000 import GREATER_THAN_SIGN
from celestine.unicode.u0000 import QUESTION_MARK
from celestine.unicode.u0000 import LEFT_SQUARE_BRACKET
from celestine.unicode.u0000 import RIGHT_SQUARE_BRACKET
from celestine.unicode.u0000 import LEFT_CURLY_BRACKET
from celestine.unicode.u0000 import VERTICAL_LINE
from celestine.unicode.u0000 import RIGHT_CURLY_BRACKET
from celestine.unicode.u0000 import LEFT_PARENTHESIS
from celestine.unicode.u0000 import RIGHT_PARENTHESIS

DINGBATS = {
    BLACK_SAFETY_SCISSORS: None,
    UPPER_BLADE_SCISSORS: None,
    BLACK_SCISSORS: None,
    LOWER_BLADE_SCISSORS: None,
    WHITE_SCISSORS: None,
    WHITE_HEAVY_CHECK_MARK: None,
    TELEPHONE_LOCATION_SIGN: None,
    TAPE_DRIVE: None,
    AIRPLANE: None,
    ENVELOPE: None,
    RAISED_FIST: None,
    RAISED_HAND: None,
    VICTORY_HAND: None,
    WRITING_HAND: None,
    LOWER_RIGHT_PENCIL: None,
    PENCIL: None,
    UPPER_RIGHT_PENCIL: None,
    WHITE_NIB: None,
    BLACK_NIB: None,
    CHECK_MARK: None,
    HEAVY_CHECK_MARK: None,
    MULTIPLICATION_X: ASTERISK,
    HEAVY_MULTIPLICATION_X: ASTERISK,
    BALLOT_X: None,
    HEAVY_BALLOT_X: None,
    OUTLINED_GREEK_CROSS: None,
    HEAVY_GREEK_CROSS: None,
    OPEN_CENTRE_CROSS: None,
    HEAVY_OPEN_CENTRE_CROSS: None,
    LATIN_CROSS: None,
    SHADOWED_WHITE_LATIN_CROSS: None,
    OUTLINED_LATIN_CROSS: None,
    MALTESE_CROSS: None,
    STAR_OF_DAVID: None,
    FOUR_TEARDROP_SPOKED_ASTERISK: None,
    FOUR_BALLOON_SPOKED_ASTERISK: None,
    HEAVY_FOUR_BALLOON_SPOKED_ASTERISK: None,
    FOUR_CLUB_SPOKED_ASTERISK: None,
    BLACK_FOUR_POINTED_STAR: None,
    WHITE_FOUR_POINTED_STAR: None,
    SPARKLES: None,
    STRESS_OUTLINED_WHITE_STAR: None,
    CIRCLED_WHITE_STAR: None,
    OPEN_CENTRE_BLACK_STAR: None,
    BLACK_CENTRE_WHITE_STAR: None,
    OUTLINED_BLACK_STAR: None,
    HEAVY_OUTLINED_BLACK_STAR: None,
    PINWHEEL_STAR: None,
    SHADOWED_WHITE_STAR: None,
    HEAVY_ASTERISK: None,
    OPEN_CENTRE_ASTERISK: None,
    EIGHT_SPOKED_ASTERISK: None,
    EIGHT_POINTED_BLACK_STAR: None,
    EIGHT_POINTED_PINWHEEL_STAR: None,
    SIX_POINTED_BLACK_STAR: None,
    EIGHT_POINTED_RECTILINEAR_BLACK_STAR: None,
    HEAVY_EIGHT_POINTED_RECTILINEAR_BLACK_STAR: None,
    TWELVE_POINTED_BLACK_STAR: None,
    SIXTEEN_POINTED_ASTERISK: None,
    TEARDROP_SPOKED_ASTERISK: None,
    OPEN_CENTRE_TEARDROP_SPOKED_ASTERISK: None,
    HEAVY_TEARDROP_SPOKED_ASTERISK: None,
    SIX_PETALLED_BLACK_AND_WHITE_FLORETTE: None,
    BLACK_FLORETTE: None,
    WHITE_FLORETTE: None,
    EIGHT_PETALLED_OUTLINED_BLACK_FLORETTE: None,
    CIRCLED_OPEN_CENTRE_EIGHT_POINTED_STAR: None,
    HEAVY_TEARDROP_SPOKED_PINWHEEL_ASTERISK: None,
    SNOWFLAKE: None,
    TIGHT_TRIFOLIATE_SNOWFLAKE: None,
    HEAVY_CHEVRON_SNOWFLAKE: None,
    SPARKLE: None,
    HEAVY_SPARKLE: None,
    BALLOON_SPOKED_ASTERISK: None,
    EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK: None,
    HEAVY_EIGHT_TEARDROP_SPOKED_PROPELLER_ASTERISK: None,
    CROSS_MARK: ASTERISK,
    SHADOWED_WHITE_CIRCLE: None,
    NEGATIVE_SQUARED_CROSS_MARK: None,
    LOWER_RIGHT_DROP_SHADOWED_WHITE_SQUARE: None,
    UPPER_RIGHT_DROP_SHADOWED_WHITE_SQUARE: None,
    LOWER_RIGHT_SHADOWED_WHITE_SQUARE: None,
    UPPER_RIGHT_SHADOWED_WHITE_SQUARE: None,
    BLACK_QUESTION_MARK_ORNAMENT: QUESTION_MARK,
    WHITE_QUESTION_MARK_ORNAMENT: QUESTION_MARK,
    WHITE_EXCLAMATION_MARK_ORNAMENT: EXCLAMATION_MARK,
    BLACK_DIAMOND_MINUS_WHITE_X: None,
    HEAVY_EXCLAMATION_MARK_SYMBOL: None,
    LIGHT_VERTICAL_BAR: VERTICAL_LINE,
    MEDIUM_VERTICAL_BAR: VERTICAL_LINE,
    HEAVY_VERTICAL_BAR: VERTICAL_LINE,
    HEAVY_SINGLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT: APOSTROPHE,
    HEAVY_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT: APOSTROPHE,
    HEAVY_DOUBLE_TURNED_COMMA_QUOTATION_MARK_ORNAMENT: QUOTATION_MARK,
    HEAVY_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT: QUOTATION_MARK,
    HEAVY_LOW_SINGLE_COMMA_QUOTATION_MARK_ORNAMENT: APOSTROPHE,
    HEAVY_LOW_DOUBLE_COMMA_QUOTATION_MARK_ORNAMENT: QUOTATION_MARK,
    CURVED_STEM_PARAGRAPH_SIGN_ORNAMENT: None,
    HEAVY_EXCLAMATION_MARK_ORNAMENT: EXCLAMATION_MARK,
    HEAVY_HEART_EXCLAMATION_MARK_ORNAMENT: EXCLAMATION_MARK,
    HEAVY_BLACK_HEART: None,
    ROTATED_HEAVY_BLACK_HEART_BULLET: None,
    FLORAL_HEART: None,
    ROTATED_FLORAL_HEART_BULLET: None,
    MEDIUM_LEFT_PARENTHESIS_ORNAMENT: LEFT_PARENTHESIS,
    MEDIUM_RIGHT_PARENTHESIS_ORNAMENT: RIGHT_PARENTHESIS,
    MEDIUM_FLATTENED_LEFT_PARENTHESIS_ORNAMENT: LEFT_PARENTHESIS,
    MEDIUM_FLATTENED_RIGHT_PARENTHESIS_ORNAMENT: RIGHT_PARENTHESIS,
    MEDIUM_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT: LESS_THAN_SIGN,
    MEDIUM_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT: GREATER_THAN_SIGN,
    HEAVY_LEFT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT: QUOTATION_MARK,
    HEAVY_RIGHT_POINTING_ANGLE_QUOTATION_MARK_ORNAMENT: QUOTATION_MARK,
    HEAVY_LEFT_POINTING_ANGLE_BRACKET_ORNAMENT: LESS_THAN_SIGN,
    HEAVY_RIGHT_POINTING_ANGLE_BRACKET_ORNAMENT: GREATER_THAN_SIGN,
    LIGHT_LEFT_TORTOISE_SHELL_BRACKET_ORNAMENT: LEFT_SQUARE_BRACKET,
    LIGHT_RIGHT_TORTOISE_SHELL_BRACKET_ORNAMENT: RIGHT_SQUARE_BRACKET,
    MEDIUM_LEFT_CURLY_BRACKET_ORNAMENT: LEFT_CURLY_BRACKET,
    MEDIUM_RIGHT_CURLY_BRACKET_ORNAMENT: RIGHT_CURLY_BRACKET,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_ONE: DIGIT_ONE,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_TWO: DIGIT_TWO,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_THREE: DIGIT_THREE,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_FOUR: DIGIT_FOUR,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_FIVE: DIGIT_FIVE,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_SIX: DIGIT_SIX,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_SEVEN: DIGIT_SEVEN,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_EIGHT: DIGIT_EIGHT,
    DINGBAT_NEGATIVE_CIRCLED_DIGIT_NINE: DIGIT_NINE,
    DINGBAT_NEGATIVE_CIRCLED_NUMBER_TEN: DIGIT_ZERO,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_ONE: DIGIT_ONE,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_TWO: DIGIT_TWO,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_THREE: DIGIT_THREE,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FOUR: DIGIT_FOUR,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_FIVE: DIGIT_FIVE,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SIX: DIGIT_SIX,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_SEVEN: DIGIT_SEVEN,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_EIGHT: DIGIT_EIGHT,
    DINGBAT_CIRCLED_SANS_SERIF_DIGIT_NINE: DIGIT_NINE,
    DINGBAT_CIRCLED_SANS_SERIF_NUMBER_TEN: DIGIT_ZERO,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_ONE: DIGIT_ONE,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_TWO: DIGIT_TWO,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_THREE: DIGIT_THREE,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FOUR: DIGIT_FOUR,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_FIVE: DIGIT_FIVE,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SIX: DIGIT_SIX,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_SEVEN: DIGIT_SEVEN,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_EIGHT: DIGIT_EIGHT,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_DIGIT_NINE: DIGIT_NINE,
    DINGBAT_NEGATIVE_CIRCLED_SANS_SERIF_NUMBER_TEN: DIGIT_ZERO,
    HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW: None,
    HEAVY_PLUS_SIGN: PLUS_SIGN,
    HEAVY_MINUS_SIGN: HYPHEN_MINUS,
    HEAVY_DIVISION_SIGN: SOLIDUS,
    HEAVY_SOUTH_EAST_ARROW: None,
    HEAVY_RIGHTWARDS_ARROW: None,
    HEAVY_NORTH_EAST_ARROW: None,
    DRAFTING_POINT_RIGHTWARDS_ARROW: None,
    HEAVY_ROUND_TIPPED_RIGHTWARDS_ARROW: None,
    TRIANGLE_HEADED_RIGHTWARDS_ARROW: None,
    HEAVY_TRIANGLE_HEADED_RIGHTWARDS_ARROW: None,
    DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW: None,
    HEAVY_DASHED_TRIANGLE_HEADED_RIGHTWARDS_ARROW: None,
    BLACK_RIGHTWARDS_ARROW: None,
    THREE_D_TOP_LIGHTED_RIGHTWARDS_ARROWHEAD: None,
    THREE_D_BOTTOM_LIGHTED_RIGHTWARDS_ARROWHEAD: None,
    BLACK_RIGHTWARDS_ARROWHEAD: None,
    HEAVY_BLACK_CURVED_DOWNWARDS_AND_RIGHTWARDS_ARROW: None,
    HEAVY_BLACK_CURVED_UPWARDS_AND_RIGHTWARDS_ARROW: None,
    SQUAT_BLACK_RIGHTWARDS_ARROW: None,
    HEAVY_CONCAVE_POINTED_BLACK_RIGHTWARDS_ARROW: None,
    RIGHT_SHADED_WHITE_RIGHTWARDS_ARROW: None,
    LEFT_SHADED_WHITE_RIGHTWARDS_ARROW: None,
    BACK_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW: None,
    FRONT_TILTED_SHADOWED_WHITE_RIGHTWARDS_ARROW: None,
    HEAVY_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: None,
    HEAVY_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: None,
    NOTCHED_LOWER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: None,
    CURLY_LOOP: None,
    NOTCHED_UPPER_RIGHT_SHADOWED_WHITE_RIGHTWARDS_ARROW: None,
    CIRCLED_HEAVY_WHITE_RIGHTWARDS_ARROW: None,
    WHITE_FEATHERED_RIGHTWARDS_ARROW: None,
    BLACK_FEATHERED_SOUTH_EAST_ARROW: None,
    BLACK_FEATHERED_RIGHTWARDS_ARROW: None,
    BLACK_FEATHERED_NORTH_EAST_ARROW: None,
    HEAVY_BLACK_FEATHERED_SOUTH_EAST_ARROW: None,
    HEAVY_BLACK_FEATHERED_RIGHTWARDS_ARROW: None,
    HEAVY_BLACK_FEATHERED_NORTH_EAST_ARROW: None,
    TEARDROP_BARBED_RIGHTWARDS_ARROW: None,
    HEAVY_TEARDROP_SHANKED_RIGHTWARDS_ARROW: None,
    WEDGE_TAILED_RIGHTWARDS_ARROW: None,
    HEAVY_WEDGE_TAILED_RIGHTWARDS_ARROW: None,
    OPEN_OUTLINED_RIGHTWARDS_ARROW: None,
    DOUBLE_CURLY_LOOP: None
}
