/* JSLint edition 2019-01-31 */
/*jslint
    browser:true
*/
/*global
    UTF_8
*/
/*property
    $, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X,
    Y, Z, _
*/
const UTF_8 = {
    " ": "SPACE",
    "!": "EXCLAMATION_MARK",
    "\"": "QUOTATION_MARK",
    "#": "NUMBER_SIGN",
    "$": "DOLLAR_SIGN",
    "%": "PERCENT_SIGN",
    "&": "AMPERSAND",
    "'": "APOSTROPHE",
    "(": "LEFT_PARENTHESIS",
    ")": "RIGHT_PARENTHESIS",
    "*": "ASTERISK",
    "+": "PLUS_SIGN",
    ",": "COMMA",
    "-": "HYPHEN_MINUS",
    ".": "FULL_STOP",
    "/": "SOLIDUS",
    "0": "DIGIT_ZERO",
    "1": "DIGIT_ONE",
    "2": "DIGIT_TWO",
    "3": "DIGIT_THREE",
    "4": "DIGIT_FOUR",
    "5": "DIGIT_FIVE",
    "6": "DIGIT_SIX",
    "7": "DIGIT_SEVEN",
    "8": "DIGIT_EIGHT",
    "9": "DIGIT_NINE",
    ":": "COLON",
    ";": "SEMICOLON",
    "<": "LESS_THAN_SIGN",
    "=": "EQUALS_SIGN",
    ">": "GREATER_THAN_SIGN",
    "?": "QUESTION_MARK",
    "@": "COMMERCIA_AT",
    "A": "LATIN_CAPITAL_LETTER_A",
    "B": "LATIN_CAPITAL_LETTER_B",
    "C": "LATIN_CAPITAL_LETTER_C",
    "D": "LATIN_CAPITAL_LETTER_D",
    "E": "LATIN_CAPITAL_LETTER_E",
    "F": "LATIN_CAPITAL_LETTER_F",
    "G": "LATIN_CAPITAL_LETTER_G",
    "H": "LATIN_CAPITAL_LETTER_H",
    "I": "LATIN_CAPITAL_LETTER_I",
    "J": "LATIN_CAPITAL_LETTER_J",
    "K": "LATIN_CAPITAL_LETTER_K",
    "L": "LATIN_CAPITAL_LETTER_L",
    "M": "LATIN_CAPITAL_LETTER_M",
    "N": "LATIN_CAPITAL_LETTER_N",
    "O": "LATIN_CAPITAL_LETTER_O",
    "P": "LATIN_CAPITAL_LETTER_P",
    "Q": "LATIN_CAPITAL_LETTER_Q",
    "R": "LATIN_CAPITAL_LETTER_R",
    "S": "LATIN_CAPITAL_LETTER_S",
    "T": "LATIN_CAPITAL_LETTER_T",
    "U": "LATIN_CAPITAL_LETTER_U",
    "V": "LATIN_CAPITAL_LETTER_V",
    "W": "LATIN_CAPITAL_LETTER_W",
    "X": "LATIN_CAPITAL_LETTER_X",
    "Y": "LATIN_CAPITAL_LETTER_Y",
    "Z": "LATIN_CAPITAL_LETTER_Z",
    "[": "LEFT_SQUARE_BRACKET",
    "\\": "REVERSE_SOLIDUS",
    "]": "RIGHT_SQUARE_BRACKET",
    "^": "CIRCUMFLEX_ACCENT",
    "_": "LOW_LINE",
    "`": "GRAVE_ACCENT"
};