/* JSLint edition 2019-01-31 */
/*jslint
    browser:true
*/
/*global
    CHARACTER_CODE, CHARACTER_NAME
*/
/*property
    AMPERSAND, APOSTROPHE, ASTERISK, CIRCUMFLEX_ACCENT, COLON, COMMA,
    COMMERCIA_AT, DIGIT_EIGHT, DIGIT_FIVE, DIGIT_FOUR, DIGIT_NINE, DIGIT_ONE,
    DIGIT_SEVEN, DIGIT_SIX, DIGIT_THREE, DIGIT_TWO, DIGIT_ZERO, DOLLAR_SIGN,
    EQUALS_SIGN, EXCLAMATION_MARK, FULL_STOP, GRAVE_ACCENT, GREATER_THAN_SIGN,
    HYPHEN_MINUS, LATIN_CAPITAL_LETTER_A, LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C, LATIN_CAPITAL_LETTER_D, LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F, LATIN_CAPITAL_LETTER_G, LATIN_CAPITAL_LETTER_H,
    LATIN_CAPITAL_LETTER_I, LATIN_CAPITAL_LETTER_J, LATIN_CAPITAL_LETTER_K,
    LATIN_CAPITAL_LETTER_L, LATIN_CAPITAL_LETTER_M, LATIN_CAPITAL_LETTER_N,
    LATIN_CAPITAL_LETTER_O, LATIN_CAPITAL_LETTER_P, LATIN_CAPITAL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R, LATIN_CAPITAL_LETTER_S, LATIN_CAPITAL_LETTER_T,
    LATIN_CAPITAL_LETTER_U, LATIN_CAPITAL_LETTER_V, LATIN_CAPITAL_LETTER_W,
    LATIN_CAPITAL_LETTER_X, LATIN_CAPITAL_LETTER_Y, LATIN_CAPITAL_LETTER_Z,
    LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LESS_THAN_SIGN, LOW_LINE,
    NUMBER_SIGN, PERCENT_SIGN, PLUS_SIGN, QUESTION_MARK, QUOTATION_MARK,
    REVERSE_SOLIDUS, RIGHT_PARENTHESIS, RIGHT_SQUARE_BRACKET, SEMICOLON,
    SOLIDUS, SPACE
*/