"""Keywords used throughout the translator application."""

INIT = "__init__"
KEY = "key"
LANGUAGE = "language"
LANGUAGE_TAG_AZURE = "LANGUAGE_TAG_AZURE"
LANGUAGE_NAME_ENGLISH = "LANGUAGE_NAME_ENGLISH"
LANGUAGE_TAG_ISO = "LANGUAGE_TAG_ISO"
LANGUAGE_NAME_NATIVE = "LANGUAGE_NAME_NATIVE"
REGION = "region"
SESSION = "session"

TEXT = "text"
TO = "to"
TRANSLATIONS = "translations"
URL = "url"
