from Unicode.U0000 import NULL
from Unicode.U0000 import START_OF_HEADING
from Unicode.U0000 import START_OF_TEXT
from Unicode.U0000 import END_OF_TEXT
from Unicode.U0000 import END_OF_TRANSMISSION
from Unicode.U0000 import ENQUIRY
from Unicode.U0000 import ACKNOWLEDGE
from Unicode.U0000 import BELL
from Unicode.U0000 import BACKSPACE
from Unicode.U0000 import CHARACTER_TABULATION
from Unicode.U0000 import LINE_FEED
from Unicode.U0000 import LINE_TABULATION
from Unicode.U0000 import FORM_FEED
from Unicode.U0000 import CARRIAGE_RETURN
from Unicode.U0000 import SHIFT_OUT
from Unicode.U0000 import SHIFT_IN
from Unicode.U0000 import DATA_LINK_ESCAPE
from Unicode.U0000 import DEVICE_CONTROL_ONE
from Unicode.U0000 import DEVICE_CONTROL_TWO
from Unicode.U0000 import DEVICE_CONTROL_THREE
from Unicode.U0000 import DEVICE_CONTROL_FOUR
from Unicode.U0000 import NEGATIVE_ACKNOWLEDGE
from Unicode.U0000 import SYNCHRONOUS_IDLE
from Unicode.U0000 import END_OF_TRANSMISSION_BLOCK
from Unicode.U0000 import CANCEL
from Unicode.U0000 import END_OF_MEDIUM
from Unicode.U0000 import SUBSTITUTE
from Unicode.U0000 import ESCAPE
from Unicode.U0000 import INFORMATION_SEPARATOR_FOUR
from Unicode.U0000 import INFORMATION_SEPARATOR_THREE
from Unicode.U0000 import INFORMATION_SEPARATOR_TWO
from Unicode.U0000 import INFORMATION_SEPARATOR_ONE
from Unicode.U0000 import SPACE
from Unicode.U0000 import EXCLAMATION_MARK
from Unicode.U0000 import QUOTATION_MARK
from Unicode.U0000 import NUMBER_SIGN
from Unicode.U0000 import DOLLAR_SIGN
from Unicode.U0000 import PERCENT_SIGN
from Unicode.U0000 import AMPERSAND
from Unicode.U0000 import APOSTROPHE
from Unicode.U0000 import LEFT_PARENTHESIS
from Unicode.U0000 import RIGHT_PARENTHESIS
from Unicode.U0000 import ASTERISK
from Unicode.U0000 import PLUS_SIGN
from Unicode.U0000 import COMMA
from Unicode.U0000 import HYPHEN_MINUS
from Unicode.U0000 import FULL_STOP
from Unicode.U0000 import SOLIDUS
from Unicode.U0000 import DIGIT_ZERO
from Unicode.U0000 import DIGIT_ONE
from Unicode.U0000 import DIGIT_TWO
from Unicode.U0000 import DIGIT_THREE
from Unicode.U0000 import DIGIT_FOUR
from Unicode.U0000 import DIGIT_FIVE
from Unicode.U0000 import DIGIT_SIX
from Unicode.U0000 import DIGIT_SEVEN
from Unicode.U0000 import DIGIT_EIGHT
from Unicode.U0000 import DIGIT_NINE
from Unicode.U0000 import COLON
from Unicode.U0000 import SEMICOLON
from Unicode.U0000 import LESS_THAN_SIGN
from Unicode.U0000 import EQUALS_SIGN
from Unicode.U0000 import GREATER_THAN_SIGN
from Unicode.U0000 import QUESTION_MARK
from Unicode.U0000 import COMMERCIA_AT
from Unicode.U0000 import LATIN_CAPITAL_LETTER_A
from Unicode.U0000 import LATIN_CAPITAL_LETTER_B
from Unicode.U0000 import LATIN_CAPITAL_LETTER_C
from Unicode.U0000 import LATIN_CAPITAL_LETTER_D
from Unicode.U0000 import LATIN_CAPITAL_LETTER_E
from Unicode.U0000 import LATIN_CAPITAL_LETTER_F
from Unicode.U0000 import LATIN_CAPITAL_LETTER_G
from Unicode.U0000 import LATIN_CAPITAL_LETTER_H
from Unicode.U0000 import LATIN_CAPITAL_LETTER_I
from Unicode.U0000 import LATIN_CAPITAL_LETTER_J
from Unicode.U0000 import LATIN_CAPITAL_LETTER_K
from Unicode.U0000 import LATIN_CAPITAL_LETTER_L
from Unicode.U0000 import LATIN_CAPITAL_LETTER_M
from Unicode.U0000 import LATIN_CAPITAL_LETTER_N
from Unicode.U0000 import LATIN_CAPITAL_LETTER_O
from Unicode.U0000 import LATIN_CAPITAL_LETTER_P
from Unicode.U0000 import LATIN_CAPITAL_LETTER_Q
from Unicode.U0000 import LATIN_CAPITAL_LETTER_R
from Unicode.U0000 import LATIN_CAPITAL_LETTER_S
from Unicode.U0000 import LATIN_CAPITAL_LETTER_T
from Unicode.U0000 import LATIN_CAPITAL_LETTER_U
from Unicode.U0000 import LATIN_CAPITAL_LETTER_V
from Unicode.U0000 import LATIN_CAPITAL_LETTER_W
from Unicode.U0000 import LATIN_CAPITAL_LETTER_X
from Unicode.U0000 import LATIN_CAPITAL_LETTER_Y
from Unicode.U0000 import LATIN_CAPITAL_LETTER_Z
from Unicode.U0000 import LEFT_SQUARE_BRACKET
from Unicode.U0000 import REVERSE_SOLIDUS
from Unicode.U0000 import RIGHT_SQUARE_BRACKET
from Unicode.U0000 import CIRCUMFLEX_ACCENT
from Unicode.U0000 import LOW_LINE
from Unicode.U0000 import GRAVE_ACCENT
from Unicode.U0000 import LATIN_SMALL_LETTER_A
from Unicode.U0000 import LATIN_SMALL_LETTER_B
from Unicode.U0000 import LATIN_SMALL_LETTER_C
from Unicode.U0000 import LATIN_SMALL_LETTER_D
from Unicode.U0000 import LATIN_SMALL_LETTER_E
from Unicode.U0000 import LATIN_SMALL_LETTER_F
from Unicode.U0000 import LATIN_SMALL_LETTER_G
from Unicode.U0000 import LATIN_SMALL_LETTER_H
from Unicode.U0000 import LATIN_SMALL_LETTER_I
from Unicode.U0000 import LATIN_SMALL_LETTER_J
from Unicode.U0000 import LATIN_SMALL_LETTER_K
from Unicode.U0000 import LATIN_SMALL_LETTER_L
from Unicode.U0000 import LATIN_SMALL_LETTER_M
from Unicode.U0000 import LATIN_SMALL_LETTER_N
from Unicode.U0000 import LATIN_SMALL_LETTER_O
from Unicode.U0000 import LATIN_SMALL_LETTER_P
from Unicode.U0000 import LATIN_SMALL_LETTER_Q
from Unicode.U0000 import LATIN_SMALL_LETTER_R
from Unicode.U0000 import LATIN_SMALL_LETTER_S
from Unicode.U0000 import LATIN_SMALL_LETTER_T
from Unicode.U0000 import LATIN_SMALL_LETTER_U
from Unicode.U0000 import LATIN_SMALL_LETTER_V
from Unicode.U0000 import LATIN_SMALL_LETTER_W
from Unicode.U0000 import LATIN_SMALL_LETTER_X
from Unicode.U0000 import LATIN_SMALL_LETTER_Y
from Unicode.U0000 import LATIN_SMALL_LETTER_Z
from Unicode.U0000 import LEFT_CURLY_BRACKET
from Unicode.U0000 import VERTICAL_LINE
from Unicode.U0000 import RIGHT_CURLY_BRACKET
from Unicode.U0000 import TILDE
from Unicode.U0000 import DELETE


C0_CONTROLS_AND_BASIC_LATIN = {
    NULL: None,
    START_OF_HEADING: None,
    START_OF_TEXT: None,
    END_OF_TEXT: None,
    END_OF_TRANSMISSION: None,
    ENQUIRY: None,
    ACKNOWLEDGE: None,
    BELL: None,
    BACKSPACE: None,
    CHARACTER_TABULATION: SPACE,
    LINE_FEED: None,
    LINE_TABULATION: None,
    FORM_FEED: None,
    CARRIAGE_RETURN: None,
    SHIFT_OUT: None,
    SHIFT_IN: None,
    DATA_LINK_ESCAPE: None,
    DEVICE_CONTROL_ONE: None,
    DEVICE_CONTROL_TWO: None,
    DEVICE_CONTROL_THREE: None,
    DEVICE_CONTROL_FOUR: None,
    NEGATIVE_ACKNOWLEDGE: None,
    SYNCHRONOUS_IDLE: None,
    END_OF_TRANSMISSION_BLOCK: None,
    CANCEL: None,
    END_OF_MEDIUM: None,
    SUBSTITUTE: None,
    ESCAPE: None,
    INFORMATION_SEPARATOR_FOUR: None,
    INFORMATION_SEPARATOR_THREE: None,
    INFORMATION_SEPARATOR_TWO: None,
    INFORMATION_SEPARATOR_ONE: None,
    SPACE: SPACE,
    EXCLAMATION_MARK: EXCLAMATION_MARK,
    QUOTATION_MARK: QUOTATION_MARK,
    NUMBER_SIGN: NUMBER_SIGN,
    DOLLAR_SIGN: DOLLAR_SIGN,
    PERCENT_SIGN: PERCENT_SIGN,
    AMPERSAND: AMPERSAND,
    APOSTROPHE: APOSTROPHE,
    LEFT_PARENTHESIS: LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS: RIGHT_PARENTHESIS,
    ASTERISK: ASTERISK,
    PLUS_SIGN: PLUS_SIGN,
    COMMA: COMMA,
    HYPHEN_MINUS: HYPHEN_MINUS,
    FULL_STOP: FULL_STOP,
    SOLIDUS: SOLIDUS,
    DIGIT_ZERO: DIGIT_ZERO,
    DIGIT_ONE: DIGIT_ONE,
    DIGIT_TWO: DIGIT_TWO,
    DIGIT_THREE: DIGIT_THREE,
    DIGIT_FOUR: DIGIT_FOUR,
    DIGIT_FIVE: DIGIT_FIVE,
    DIGIT_SIX: DIGIT_SIX,
    DIGIT_SEVEN: DIGIT_SEVEN,
    DIGIT_EIGHT: DIGIT_EIGHT,
    DIGIT_NINE: DIGIT_NINE,
    COLON: COLON,
    SEMICOLON: SEMICOLON,
    LESS_THAN_SIGN: LESS_THAN_SIGN,
    EQUALS_SIGN: EQUALS_SIGN,
    GREATER_THAN_SIGN: GREATER_THAN_SIGN,
    QUESTION_MARK: QUESTION_MARK,
    COMMERCIA_AT: COMMERCIA_AT,
    LATIN_CAPITAL_LETTER_A: LATIN_CAPITAL_LETTER_A,
    LATIN_CAPITAL_LETTER_B: LATIN_CAPITAL_LETTER_B,
    LATIN_CAPITAL_LETTER_C: LATIN_CAPITAL_LETTER_C,
    LATIN_CAPITAL_LETTER_D: LATIN_CAPITAL_LETTER_D,
    LATIN_CAPITAL_LETTER_E: LATIN_CAPITAL_LETTER_E,
    LATIN_CAPITAL_LETTER_F: LATIN_CAPITAL_LETTER_F,
    LATIN_CAPITAL_LETTER_G: LATIN_CAPITAL_LETTER_G,
    LATIN_CAPITAL_LETTER_H: LATIN_CAPITAL_LETTER_H,
    LATIN_CAPITAL_LETTER_I: LATIN_CAPITAL_LETTER_I,
    LATIN_CAPITAL_LETTER_J: LATIN_CAPITAL_LETTER_J,
    LATIN_CAPITAL_LETTER_K: LATIN_CAPITAL_LETTER_K,
    LATIN_CAPITAL_LETTER_L: LATIN_CAPITAL_LETTER_L,
    LATIN_CAPITAL_LETTER_M: LATIN_CAPITAL_LETTER_M,
    LATIN_CAPITAL_LETTER_N: LATIN_CAPITAL_LETTER_N,
    LATIN_CAPITAL_LETTER_O: LATIN_CAPITAL_LETTER_O,
    LATIN_CAPITAL_LETTER_P: LATIN_CAPITAL_LETTER_P,
    LATIN_CAPITAL_LETTER_Q: LATIN_CAPITAL_LETTER_Q,
    LATIN_CAPITAL_LETTER_R: LATIN_CAPITAL_LETTER_R,
    LATIN_CAPITAL_LETTER_S: LATIN_CAPITAL_LETTER_S,
    LATIN_CAPITAL_LETTER_T: LATIN_CAPITAL_LETTER_T,
    LATIN_CAPITAL_LETTER_U: LATIN_CAPITAL_LETTER_U,
    LATIN_CAPITAL_LETTER_V: LATIN_CAPITAL_LETTER_V,
    LATIN_CAPITAL_LETTER_W: LATIN_CAPITAL_LETTER_W,
    LATIN_CAPITAL_LETTER_X: LATIN_CAPITAL_LETTER_X,
    LATIN_CAPITAL_LETTER_Y: LATIN_CAPITAL_LETTER_Y,
    LATIN_CAPITAL_LETTER_Z: LATIN_CAPITAL_LETTER_Z,
    LEFT_SQUARE_BRACKET: LEFT_SQUARE_BRACKET,
    REVERSE_SOLIDUS: REVERSE_SOLIDUS,
    RIGHT_SQUARE_BRACKET: RIGHT_SQUARE_BRACKET,
    CIRCUMFLEX_ACCENT: CIRCUMFLEX_ACCENT,
    LOW_LINE: LOW_LINE,
    GRAVE_ACCENT: GRAVE_ACCENT,
    LATIN_SMALL_LETTER_A: LATIN_SMALL_LETTER_A,
    LATIN_SMALL_LETTER_B: LATIN_SMALL_LETTER_B,
    LATIN_SMALL_LETTER_C: LATIN_SMALL_LETTER_C,
    LATIN_SMALL_LETTER_D: LATIN_SMALL_LETTER_D,
    LATIN_SMALL_LETTER_E: LATIN_SMALL_LETTER_E,
    LATIN_SMALL_LETTER_F: LATIN_SMALL_LETTER_F,
    LATIN_SMALL_LETTER_G: LATIN_SMALL_LETTER_G,
    LATIN_SMALL_LETTER_H: LATIN_SMALL_LETTER_H,
    LATIN_SMALL_LETTER_I: LATIN_SMALL_LETTER_I,
    LATIN_SMALL_LETTER_J: LATIN_SMALL_LETTER_J,
    LATIN_SMALL_LETTER_K: LATIN_SMALL_LETTER_K,
    LATIN_SMALL_LETTER_L: LATIN_SMALL_LETTER_L,
    LATIN_SMALL_LETTER_M: LATIN_SMALL_LETTER_M,
    LATIN_SMALL_LETTER_N: LATIN_SMALL_LETTER_N,
    LATIN_SMALL_LETTER_O: LATIN_SMALL_LETTER_O,
    LATIN_SMALL_LETTER_P: LATIN_SMALL_LETTER_P,
    LATIN_SMALL_LETTER_Q: LATIN_SMALL_LETTER_Q,
    LATIN_SMALL_LETTER_R: LATIN_SMALL_LETTER_R,
    LATIN_SMALL_LETTER_S: LATIN_SMALL_LETTER_S,
    LATIN_SMALL_LETTER_T: LATIN_SMALL_LETTER_T,
    LATIN_SMALL_LETTER_U: LATIN_SMALL_LETTER_U,
    LATIN_SMALL_LETTER_V: LATIN_SMALL_LETTER_V,
    LATIN_SMALL_LETTER_W: LATIN_SMALL_LETTER_W,
    LATIN_SMALL_LETTER_X: LATIN_SMALL_LETTER_X,
    LATIN_SMALL_LETTER_Y: LATIN_SMALL_LETTER_Y,
    LATIN_SMALL_LETTER_Z: LATIN_SMALL_LETTER_Z,
    LEFT_CURLY_BRACKET: LEFT_CURLY_BRACKET,
    VERTICAL_LINE: VERTICAL_LINE,
    RIGHT_CURLY_BRACKET: RIGHT_CURLY_BRACKET,
    TILDE: TILDE,
    DELETE: None
}
